/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type EventDefinition,
    EventDefinitionFromJSON,
    EventDefinitionToJSON,
} from '../models/EventDefinition.js';
import {
    type EventDefinitionWriteRequest,
    EventDefinitionWriteRequestFromJSON,
    EventDefinitionWriteRequestToJSON,
} from '../models/EventDefinitionWriteRequest.js';
import {
    type EventSchemaDocumentRequest,
    EventSchemaDocumentRequestFromJSON,
    EventSchemaDocumentRequestToJSON,
} from '../models/EventSchemaDocumentRequest.js';
import {
    type EventSchemaVersion,
    EventSchemaVersionFromJSON,
    EventSchemaVersionToJSON,
} from '../models/EventSchemaVersion.js';
import {
    type PaginatedEventDefinitionList,
    PaginatedEventDefinitionListFromJSON,
    PaginatedEventDefinitionListToJSON,
} from '../models/PaginatedEventDefinitionList.js';
import {
    type PaginatedEventSchemaVersionList,
    PaginatedEventSchemaVersionListFromJSON,
    PaginatedEventSchemaVersionListToJSON,
} from '../models/PaginatedEventSchemaVersionList.js';
import {
    type PatchedEventDefinitionWriteRequest,
    PatchedEventDefinitionWriteRequestFromJSON,
    PatchedEventDefinitionWriteRequestToJSON,
} from '../models/PatchedEventDefinitionWriteRequest.js';
import {
    type SchemaCheck,
    SchemaCheckFromJSON,
    SchemaCheckToJSON,
} from '../models/SchemaCheck.js';
import {
    type StandardEventCatalog,
    StandardEventCatalogFromJSON,
    StandardEventCatalogToJSON,
} from '../models/StandardEventCatalog.js';
import {
    type StandardPackInstallRequest,
    StandardPackInstallRequestFromJSON,
    StandardPackInstallRequestToJSON,
} from '../models/StandardPackInstallRequest.js';
import {
    type StandardPackInstallResult,
    StandardPackInstallResultFromJSON,
    StandardPackInstallResultToJSON,
} from '../models/StandardPackInstallResult.js';

export interface EventDefinitionsCreateRequest {
    /**
     * 
     */
    eventDefinitionWriteRequest: EventDefinitionWriteRequest;
}

export interface EventDefinitionsDestroyRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
}

export interface EventDefinitionsListRequest {
    /**
     * Cursor from the previous page.
     */
    cursor?: string;
    /**
     * Number of results to return per page.
     */
    limit?: number;
}

export interface EventDefinitionsRetrieveRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
}

export interface EventDefinitionsUpdateRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * 
     */
    patchedEventDefinitionWriteRequest?: PatchedEventDefinitionWriteRequest;
}

export interface SchemaVersionsCheckRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * 
     */
    eventSchemaDocumentRequest: EventSchemaDocumentRequest;
}

export interface SchemaVersionsCreateRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * 
     */
    eventSchemaDocumentRequest: EventSchemaDocumentRequest;
}

export interface SchemaVersionsDeprecateRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * The schema version number, e.g. 2.
     */
    version: number;
}

export interface SchemaVersionsDestroyRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * The schema version number, e.g. 2.
     */
    version: number;
}

export interface SchemaVersionsListRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * Cursor from the previous page.
     */
    cursor?: string;
    /**
     * Number of results to return per page.
     */
    limit?: number;
}

export interface SchemaVersionsPublishRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * The schema version number, e.g. 2.
     */
    version: number;
}

export interface SchemaVersionsRetrieveRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * The schema version number, e.g. 2.
     */
    version: number;
}

export interface SchemaVersionsUpdateRequest {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * The schema version number, e.g. 2.
     */
    version: number;
    /**
     * 
     */
    eventSchemaDocumentRequest: EventSchemaDocumentRequest;
    /**
     * The `ETag` from your last read of this draft. If the draft has changed since, the update answers `412` instead of overwriting it. Without the header the last write wins.
     */
    ifMatch?: string;
}

export interface StandardEventsInstallRequest {
    /**
     * 
     */
    standardPackInstallRequest: StandardPackInstallRequest;
}

/**
 * 
 */
export class EventDefinitionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for eventDefinitionsCreate without sending the request
     */
    async eventDefinitionsCreateRequestOpts(requestParameters: EventDefinitionsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventDefinitionWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'eventDefinitionWriteRequest',
                'Required parameter "eventDefinitionWriteRequest" was null or undefined when calling eventDefinitionsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventDefinitionWriteRequestToJSON(requestParameters['eventDefinitionWriteRequest']),
        };
    }

    /**
     * Add an action to the catalog. Requires the ``manage`` scope on a key that is not limited to named trails. Defining the first action turns catalog enforcement on: events with any other action name are refused from then on. Add schemas with ``schema_versions_create``.
     * Define an action
     */
    async eventDefinitionsCreateRaw(requestParameters: EventDefinitionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDefinition>> {
        const requestOptions = await this.eventDefinitionsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDefinitionFromJSON(jsonValue));
    }

    /**
     * Add an action to the catalog. Requires the ``manage`` scope on a key that is not limited to named trails. Defining the first action turns catalog enforcement on: events with any other action name are refused from then on. Add schemas with ``schema_versions_create``.
     * Define an action
     */
    async eventDefinitionsCreate(requestParameters: EventDefinitionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDefinition> {
        const response = await this.eventDefinitionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventDefinitionsDestroy without sending the request
     */
    async eventDefinitionsDestroyRequestOpts(requestParameters: EventDefinitionsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling eventDefinitionsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an action and all of its schema versions, published ones included. Requires the ``manage`` scope on a key that is not limited to named trails. Deleting the team\'s last definition turns catalog enforcement off, so any action name is accepted again. Expects no request body and answers 204 with none.
     * Delete an event definition
     */
    async eventDefinitionsDestroyRaw(requestParameters: EventDefinitionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.eventDefinitionsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an action and all of its schema versions, published ones included. Requires the ``manage`` scope on a key that is not limited to named trails. Deleting the team\'s last definition turns catalog enforcement off, so any action name is accepted again. Expects no request body and answers 204 with none.
     * Delete an event definition
     */
    async eventDefinitionsDestroy(requestParameters: EventDefinitionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.eventDefinitionsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for eventDefinitionsList without sending the request
     */
    async eventDefinitionsListRequestOpts(requestParameters: EventDefinitionsListRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The actions this team\'s catalog defines, alphabetically. Needs a team API key with any scope. A team with no definitions accepts any action name, so an empty page is not an error: it means enforcement is off. Cursor-paginated: follow ``next`` until it is ``null``.
     * List event definitions
     */
    async eventDefinitionsListRaw(requestParameters: EventDefinitionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEventDefinitionList>> {
        const requestOptions = await this.eventDefinitionsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEventDefinitionListFromJSON(jsonValue));
    }

    /**
     * The actions this team\'s catalog defines, alphabetically. Needs a team API key with any scope. A team with no definitions accepts any action name, so an empty page is not an error: it means enforcement is off. Cursor-paginated: follow ``next`` until it is ``null``.
     * List event definitions
     */
    async eventDefinitionsList(requestParameters: EventDefinitionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEventDefinitionList> {
        const response = await this.eventDefinitionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventDefinitionsRetrieve without sending the request
     */
    async eventDefinitionsRetrieveRequestOpts(requestParameters: EventDefinitionsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling eventDefinitionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One action of this team\'s catalog. Needs a team API key with any scope.
     * Retrieve an event definition
     */
    async eventDefinitionsRetrieveRaw(requestParameters: EventDefinitionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDefinition>> {
        const requestOptions = await this.eventDefinitionsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDefinitionFromJSON(jsonValue));
    }

    /**
     * One action of this team\'s catalog. Needs a team API key with any scope.
     * Retrieve an event definition
     */
    async eventDefinitionsRetrieve(requestParameters: EventDefinitionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDefinition> {
        const response = await this.eventDefinitionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventDefinitionsUpdate without sending the request
     */
    async eventDefinitionsUpdateRequestOpts(requestParameters: EventDefinitionsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling eventDefinitionsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedEventDefinitionWriteRequestToJSON(requestParameters['patchedEventDefinitionWriteRequest']),
        };
    }

    /**
     * Change any of an action\'s fields; omitted fields keep their value. Sending a new ``action`` renames it, and its schema versions go with it. Events already stored keep the name they were written with. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Update or rename an event definition
     */
    async eventDefinitionsUpdateRaw(requestParameters: EventDefinitionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventDefinition>> {
        const requestOptions = await this.eventDefinitionsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventDefinitionFromJSON(jsonValue));
    }

    /**
     * Change any of an action\'s fields; omitted fields keep their value. Sending a new ``action`` renames it, and its schema versions go with it. Events already stored keep the name they were written with. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Update or rename an event definition
     */
    async eventDefinitionsUpdate(requestParameters: EventDefinitionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventDefinition> {
        const response = await this.eventDefinitionsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsCheck without sending the request
     */
    async schemaVersionsCheckRequestOpts(requestParameters: SchemaVersionsCheckRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsCheck().'
            );
        }

        if (requestParameters['eventSchemaDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'eventSchemaDocumentRequest',
                'Required parameter "eventSchemaDocumentRequest" was null or undefined when calling schemaVersionsCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/check/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventSchemaDocumentRequestToJSON(requestParameters['eventSchemaDocumentRequest']),
        };
    }

    /**
     * Dry-run a document against the action\'s newest 50 stored events and report which it would reject; nothing is stored. Stored values are checked after redaction. Needs a team API key with any scope.
     * Check a document against recent events
     */
    async schemaVersionsCheckRaw(requestParameters: SchemaVersionsCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaCheck>> {
        const requestOptions = await this.schemaVersionsCheckRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaCheckFromJSON(jsonValue));
    }

    /**
     * Dry-run a document against the action\'s newest 50 stored events and report which it would reject; nothing is stored. Stored values are checked after redaction. Needs a team API key with any scope.
     * Check a document against recent events
     */
    async schemaVersionsCheck(requestParameters: SchemaVersionsCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaCheck> {
        const response = await this.schemaVersionsCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsCreate without sending the request
     */
    async schemaVersionsCreateRequestOpts(requestParameters: SchemaVersionsCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsCreate().'
            );
        }

        if (requestParameters['eventSchemaDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'eventSchemaDocumentRequest',
                'Required parameter "eventSchemaDocumentRequest" was null or undefined when calling schemaVersionsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EventSchemaDocumentRequestToJSON(requestParameters['eventSchemaDocumentRequest']),
        };
    }

    /**
     * Store a document as a new draft at the next version number; numbers are never reused. A draft validates nothing until it is published. To change a published version, create a draft from its document with your edit applied. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Create a draft schema version
     */
    async schemaVersionsCreateRaw(requestParameters: SchemaVersionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSchemaVersion>> {
        const requestOptions = await this.schemaVersionsCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSchemaVersionFromJSON(jsonValue));
    }

    /**
     * Store a document as a new draft at the next version number; numbers are never reused. A draft validates nothing until it is published. To change a published version, create a draft from its document with your edit applied. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Create a draft schema version
     */
    async schemaVersionsCreate(requestParameters: SchemaVersionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSchemaVersion> {
        const response = await this.schemaVersionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsDeprecate without sending the request
     */
    async schemaVersionsDeprecateRequestOpts(requestParameters: SchemaVersionsDeprecateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsDeprecate().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling schemaVersionsDeprecate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/{version}/deprecate/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Start the migration window on a superseded version: producers pinned to it are accepted until its deadline, then refused. Only a published version can be deprecated, and not the one ingest selects when an event pins nothing: publish a newer one first. Deprecating a deprecated version changes nothing. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body.
     * Deprecate a version
     */
    async schemaVersionsDeprecateRaw(requestParameters: SchemaVersionsDeprecateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSchemaVersion>> {
        const requestOptions = await this.schemaVersionsDeprecateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSchemaVersionFromJSON(jsonValue));
    }

    /**
     * Start the migration window on a superseded version: producers pinned to it are accepted until its deadline, then refused. Only a published version can be deprecated, and not the one ingest selects when an event pins nothing: publish a newer one first. Deprecating a deprecated version changes nothing. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body.
     * Deprecate a version
     */
    async schemaVersionsDeprecate(requestParameters: SchemaVersionsDeprecateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSchemaVersion> {
        const response = await this.schemaVersionsDeprecateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsDestroy without sending the request
     */
    async schemaVersionsDestroyRequestOpts(requestParameters: SchemaVersionsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsDestroy().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling schemaVersionsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/{version}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a draft. Its version number is never reused. A published version cannot be deleted. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body and answers 204 with none.
     * Delete a draft
     */
    async schemaVersionsDestroyRaw(requestParameters: SchemaVersionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.schemaVersionsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a draft. Its version number is never reused. A published version cannot be deleted. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body and answers 204 with none.
     * Delete a draft
     */
    async schemaVersionsDestroy(requestParameters: SchemaVersionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.schemaVersionsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for schemaVersionsList without sending the request
     */
    async schemaVersionsListRequestOpts(requestParameters: SchemaVersionsListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Every version of one action\'s schema, newest first, drafts and deprecated versions included. Needs a team API key with any scope. Cursor-paginated: follow ``next`` until it is ``null``.
     * List schema versions
     */
    async schemaVersionsListRaw(requestParameters: SchemaVersionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEventSchemaVersionList>> {
        const requestOptions = await this.schemaVersionsListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEventSchemaVersionListFromJSON(jsonValue));
    }

    /**
     * Every version of one action\'s schema, newest first, drafts and deprecated versions included. Needs a team API key with any scope. Cursor-paginated: follow ``next`` until it is ``null``.
     * List schema versions
     */
    async schemaVersionsList(requestParameters: SchemaVersionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEventSchemaVersionList> {
        const response = await this.schemaVersionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsPublish without sending the request
     */
    async schemaVersionsPublishRequestOpts(requestParameters: SchemaVersionsPublishRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsPublish().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling schemaVersionsPublish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/{version}/publish/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Publish a draft: ingest validates against it from now on, and the version it supersedes starts its deprecation window. Publishing a published version changes nothing. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body.
     * Publish a draft
     */
    async schemaVersionsPublishRaw(requestParameters: SchemaVersionsPublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSchemaVersion>> {
        const requestOptions = await this.schemaVersionsPublishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSchemaVersionFromJSON(jsonValue));
    }

    /**
     * Publish a draft: ingest validates against it from now on, and the version it supersedes starts its deprecation window. Publishing a published version changes nothing. Requires the ``manage`` scope on a key that is not limited to named trails. Expects no request body.
     * Publish a draft
     */
    async schemaVersionsPublish(requestParameters: SchemaVersionsPublishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSchemaVersion> {
        const response = await this.schemaVersionsPublishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsRetrieve without sending the request
     */
    async schemaVersionsRetrieveRequestOpts(requestParameters: SchemaVersionsRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsRetrieve().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling schemaVersionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/{version}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One version of an action\'s schema, with its status and an `ETag`. Needs any team API key.
     * Retrieve a schema version
     */
    async schemaVersionsRetrieveRaw(requestParameters: SchemaVersionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSchemaVersion>> {
        const requestOptions = await this.schemaVersionsRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSchemaVersionFromJSON(jsonValue));
    }

    /**
     * One version of an action\'s schema, with its status and an `ETag`. Needs any team API key.
     * Retrieve a schema version
     */
    async schemaVersionsRetrieve(requestParameters: SchemaVersionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSchemaVersion> {
        const response = await this.schemaVersionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for schemaVersionsUpdate without sending the request
     */
    async schemaVersionsUpdateRequestOpts(requestParameters: SchemaVersionsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling schemaVersionsUpdate().'
            );
        }

        if (requestParameters['version'] == null) {
            throw new runtime.RequiredError(
                'version',
                'Required parameter "version" was null or undefined when calling schemaVersionsUpdate().'
            );
        }

        if (requestParameters['eventSchemaDocumentRequest'] == null) {
            throw new runtime.RequiredError(
                'eventSchemaDocumentRequest',
                'Required parameter "eventSchemaDocumentRequest" was null or undefined when calling schemaVersionsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/event-definitions/{action}/schema-versions/{version}/`;
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));
        urlPath = urlPath.replace('{version}', encodeURIComponent(String(requestParameters['version'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EventSchemaDocumentRequestToJSON(requestParameters['eventSchemaDocumentRequest']),
        };
    }

    /**
     * Replace the whole document of a draft in place; the version number does not change. This is how fields are added, renamed and removed: read the draft, edit its `properties` and `required`, and send the document back. Send the `ETag` you read as `If-Match` so a concurrent edit is not overwritten. A published version cannot be changed. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Replace a draft\'s document
     */
    async schemaVersionsUpdateRaw(requestParameters: SchemaVersionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventSchemaVersion>> {
        const requestOptions = await this.schemaVersionsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventSchemaVersionFromJSON(jsonValue));
    }

    /**
     * Replace the whole document of a draft in place; the version number does not change. This is how fields are added, renamed and removed: read the draft, edit its `properties` and `required`, and send the document back. Send the `ETag` you read as `If-Match` so a concurrent edit is not overwritten. A published version cannot be changed. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Replace a draft\'s document
     */
    async schemaVersionsUpdate(requestParameters: SchemaVersionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventSchemaVersion> {
        const response = await this.schemaVersionsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for standardEventsInstall without sending the request
     */
    async standardEventsInstallRequestOpts(requestParameters: StandardEventsInstallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['standardPackInstallRequest'] == null) {
            throw new runtime.RequiredError(
                'standardPackInstallRequest',
                'Required parameter "standardPackInstallRequest" was null or undefined when calling standardEventsInstall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/standard-events/install/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StandardPackInstallRequestToJSON(requestParameters['standardPackInstallRequest']),
        };
    }

    /**
     * Define every action of the chosen packs for the team, each with its recommended target types and a published v1 schema. An action the team already defines, active or retired, is skipped and left untouched, so installing twice is safe. Installed schemas are the team\'s own copies: editing one needs no special step. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Install standard packs
     */
    async standardEventsInstallRaw(requestParameters: StandardEventsInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StandardPackInstallResult>> {
        const requestOptions = await this.standardEventsInstallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StandardPackInstallResultFromJSON(jsonValue));
    }

    /**
     * Define every action of the chosen packs for the team, each with its recommended target types and a published v1 schema. An action the team already defines, active or retired, is skipped and left untouched, so installing twice is safe. Installed schemas are the team\'s own copies: editing one needs no special step. Requires the ``manage`` scope on a key that is not limited to named trails.
     * Install standard packs
     */
    async standardEventsInstall(requestParameters: StandardEventsInstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StandardPackInstallResult> {
        const response = await this.standardEventsInstallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for standardEventsList without sending the request
     */
    async standardEventsListRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v0/standard-events/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Santati\'s recommended actions, grouped into packs. The catalog is the same for every team and any key scope reads it; install packs with `standard_events_install`. `schema` is the v1 document installed for each action: installing copies it into the team\'s catalog, and the copy is the team\'s own to edit like any custom schema. `ocsf` maps each action to an OCSF class and activity. Not paginated.
     * List the standard event catalog
     */
    async standardEventsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StandardEventCatalog>> {
        const requestOptions = await this.standardEventsListRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StandardEventCatalogFromJSON(jsonValue));
    }

    /**
     * Santati\'s recommended actions, grouped into packs. The catalog is the same for every team and any key scope reads it; install packs with `standard_events_install`. `schema` is the v1 document installed for each action: installing copies it into the team\'s catalog, and the copy is the team\'s own to edit like any custom schema. `ocsf` maps each action to an OCSF class and activity. Not paginated.
     * List the standard event catalog
     */
    async standardEventsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StandardEventCatalog> {
        const response = await this.standardEventsListRaw(initOverrides);
        return await response.value();
    }

}
