# coding: utf-8

# flake8: noqa
"""
    Santati

    Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from santati_core.models.audit_event import AuditEvent
from santati_core.models.error_body import ErrorBody
from santati_core.models.event_actor import EventActor
from santati_core.models.event_actor_request import EventActorRequest
from santati_core.models.event_batch_item_result import EventBatchItemResult
from santati_core.models.event_batch_request import EventBatchRequest
from santati_core.models.event_batch_result import EventBatchResult
from santati_core.models.event_definition import EventDefinition
from santati_core.models.event_definition_write_request import EventDefinitionWriteRequest
from santati_core.models.event_envelope_request import EventEnvelopeRequest
from santati_core.models.event_ingest_request import EventIngestRequest
from santati_core.models.event_schema_document_request import EventSchemaDocumentRequest
from santati_core.models.event_schema_version import EventSchemaVersion
from santati_core.models.event_target import EventTarget
from santati_core.models.event_target_request import EventTargetRequest
from santati_core.models.ocsf_mapping import OcsfMapping
from santati_core.models.paginated_audit_event_list import PaginatedAuditEventList
from santati_core.models.paginated_event_definition_list import PaginatedEventDefinitionList
from santati_core.models.paginated_event_schema_version_list import PaginatedEventSchemaVersionList
from santati_core.models.patched_event_definition_write_request import PatchedEventDefinitionWriteRequest
from santati_core.models.schema_check import SchemaCheck
from santati_core.models.schema_check_failure import SchemaCheckFailure
from santati_core.models.standard_event import StandardEvent
from santati_core.models.standard_event_catalog import StandardEventCatalog
from santati_core.models.standard_pack import StandardPack
from santati_core.models.standard_pack_install_request import StandardPackInstallRequest
from santati_core.models.standard_pack_install_result import StandardPackInstallResult

