# coding: utf-8

"""
    Santati

    Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EventSchemaVersion(BaseModel):
    """
    EventSchemaVersion
    """ # noqa: E501
    version: StrictInt = Field(description="The per-action version number; never reused, even after a draft is deleted.")
    status: StrictStr = Field(description="draft: editable, validates nothing. published: immutable, validates ingest. deprecated: a newer version superseded it; pinned producers are accepted until `deprecation_deadline`.  * `draft` - Draft * `published` - Published * `deprecated` - Deprecated")
    var_schema: Dict[str, Any] = Field(description="The JSON Schema 2020-12 document. It validates the event's `metadata`, `actor.metadata` and each `targets[].metadata`; metadata values are always strings.", alias="schema")
    published_at: Optional[StrictStr] = Field(description="When the version was published; null for a draft.")
    deprecated_at: Optional[StrictStr] = Field(description="When a newer version superseded this one; null until then.")
    deprecation_deadline: Optional[StrictStr] = Field(description="When a deprecated version stops accepting pinned traffic; null while it is not deprecated.")
    created_at: StrictStr = Field(description="When the draft was first created.")
    updated_at: StrictStr = Field(description="When the version last changed. The `ETag` tracks it.")
    __properties: ClassVar[List[str]] = ["version", "status", "schema", "published_at", "deprecated_at", "deprecation_deadline", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventSchemaVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['published_at'] = None

        # set to None if deprecated_at (nullable) is None
        # and model_fields_set contains the field
        if self.deprecated_at is None and "deprecated_at" in self.model_fields_set:
            _dict['deprecated_at'] = None

        # set to None if deprecation_deadline (nullable) is None
        # and model_fields_set contains the field
        if self.deprecation_deadline is None and "deprecation_deadline" in self.model_fields_set:
            _dict['deprecation_deadline'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventSchemaVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "status": obj.get("status"),
            "schema": obj.get("schema"),
            "published_at": obj.get("published_at"),
            "deprecated_at": obj.get("deprecated_at"),
            "deprecation_deadline": obj.get("deprecation_deadline"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


