# coding: utf-8

"""
    Santati

    Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from santati_core.models.ocsf_mapping import OcsfMapping
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StandardEvent(BaseModel):
    """
    StandardEvent
    """ # noqa: E501
    action: StrictStr = Field(description="The action name, e.g. agent.tool.called.")
    description: StrictStr = Field(description="What the action means.")
    target_types: List[StrictStr] = Field(description="Target types installed as the action's allowed target types; empty means any.")
    required_metadata: List[StrictStr] = Field(description="Metadata keys every event with this action must carry.")
    optional_metadata: List[StrictStr] = Field(description="Metadata keys the schema declares as strings but does not require.")
    var_schema: Dict[str, Any] = Field(description="The JSON Schema 2020-12 document installed as the action's published v1.", alias="schema")
    ocsf: OcsfMapping = Field(description="The action's OCSF class and activity.")
    __properties: ClassVar[List[str]] = ["action", "description", "target_types", "required_metadata", "optional_metadata", "schema", "ocsf"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StandardEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ocsf
        if self.ocsf:
            _dict['ocsf'] = self.ocsf.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StandardEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "description": obj.get("description"),
            "target_types": obj.get("target_types"),
            "required_metadata": obj.get("required_metadata"),
            "optional_metadata": obj.get("optional_metadata"),
            "schema": obj.get("schema"),
            "ocsf": OcsfMapping.from_dict(obj["ocsf"]) if obj.get("ocsf") is not None else None
        })
        return _obj


