=begin
#Santati

#Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

The version of the OpenAPI document: 0.2.1

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SantatiCore
  class AuditEvent < ApiModelBase
    # The producer's event id, or a generated ULID when none was sent.
    attr_accessor :id

    # The audit log trail the event was indexed on.
    attr_accessor :trail

    # The event type, e.g. invoice.voided.
    attr_accessor :event

    # RFC 3339, when the producer says the event happened.
    attr_accessor :created_at

    # RFC 3339, when Santati indexed the event.
    attr_accessor :received_at

    # The end-customer organization the producer attributed the event to; empty when none.
    attr_accessor :organization_id

    # Who acted: the actor columns first, the producer's payload behind them.
    attr_accessor :actor

    # The objects this event acted on, in the producer's order.
    attr_accessor :targets

    # The event's own key/value map; keys and values are strings on the wire.
    attr_accessor :metadata

    # The producer's own payload for the event, stored verbatim.
    attr_accessor :data

    # The producer's extra context, stored verbatim; the read path falls back to it for `actor` and `targets` when the top-level members are absent.
    attr_accessor :context

    # sha256 of this event's chain record; empty until the seal task has run.
    attr_accessor :chain_hash

    # The event schema version the event was validated against.
    attr_accessor :schema_version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'trail' => :'trail',
        :'event' => :'event',
        :'created_at' => :'created_at',
        :'received_at' => :'received_at',
        :'organization_id' => :'organization_id',
        :'actor' => :'actor',
        :'targets' => :'targets',
        :'metadata' => :'metadata',
        :'data' => :'data',
        :'context' => :'context',
        :'chain_hash' => :'hash',
        :'schema_version' => :'schema_version'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'trail' => :'String',
        :'event' => :'String',
        :'created_at' => :'String',
        :'received_at' => :'String',
        :'organization_id' => :'String',
        :'actor' => :'EventActor',
        :'targets' => :'Array<EventTarget>',
        :'metadata' => :'Hash<String, String>',
        :'data' => :'Hash<String, Object>',
        :'context' => :'Hash<String, Object>',
        :'chain_hash' => :'String',
        :'schema_version' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'schema_version'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SantatiCore::AuditEvent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SantatiCore::AuditEvent`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'trail')
        self.trail = attributes[:'trail']
      else
        self.trail = nil
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      else
        self.event = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'received_at')
        self.received_at = attributes[:'received_at']
      else
        self.received_at = nil
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      end

      if attributes.key?(:'actor')
        self.actor = attributes[:'actor']
      else
        self.actor = nil
      end

      if attributes.key?(:'targets')
        if (value = attributes[:'targets']).is_a?(Array)
          self.targets = value
        end
      else
        self.targets = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      else
        self.metadata = nil
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      else
        self.data = nil
      end

      if attributes.key?(:'context')
        if (value = attributes[:'context']).is_a?(Hash)
          self.context = value
        end
      else
        self.context = nil
      end

      if attributes.key?(:'chain_hash')
        self.chain_hash = attributes[:'chain_hash']
      else
        self.chain_hash = nil
      end

      if attributes.key?(:'schema_version')
        self.schema_version = attributes[:'schema_version']
      else
        self.schema_version = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @trail.nil?
        invalid_properties.push('invalid value for "trail", trail cannot be nil.')
      end

      if @event.nil?
        invalid_properties.push('invalid value for "event", event cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @received_at.nil?
        invalid_properties.push('invalid value for "received_at", received_at cannot be nil.')
      end

      if @actor.nil?
        invalid_properties.push('invalid value for "actor", actor cannot be nil.')
      end

      if @targets.nil?
        invalid_properties.push('invalid value for "targets", targets cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @data.nil?
        invalid_properties.push('invalid value for "data", data cannot be nil.')
      end

      if @context.nil?
        invalid_properties.push('invalid value for "context", context cannot be nil.')
      end

      if @chain_hash.nil?
        invalid_properties.push('invalid value for "chain_hash", chain_hash cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @trail.nil?
      return false if @event.nil?
      return false if @created_at.nil?
      return false if @received_at.nil?
      return false if @actor.nil?
      return false if @targets.nil?
      return false if @metadata.nil?
      return false if @data.nil?
      return false if @context.nil?
      return false if @chain_hash.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] trail Value to be assigned
    def trail=(trail)
      if trail.nil?
        fail ArgumentError, 'trail cannot be nil'
      end

      @trail = trail
    end

    # Custom attribute writer method with validation
    # @param [Object] event Value to be assigned
    def event=(event)
      if event.nil?
        fail ArgumentError, 'event cannot be nil'
      end

      @event = event
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] received_at Value to be assigned
    def received_at=(received_at)
      if received_at.nil?
        fail ArgumentError, 'received_at cannot be nil'
      end

      @received_at = received_at
    end

    # Custom attribute writer method with validation
    # @param [Object] actor Value to be assigned
    def actor=(actor)
      if actor.nil?
        fail ArgumentError, 'actor cannot be nil'
      end

      @actor = actor
    end

    # Custom attribute writer method with validation
    # @param [Object] targets Value to be assigned
    def targets=(targets)
      if targets.nil?
        fail ArgumentError, 'targets cannot be nil'
      end

      @targets = targets
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] data Value to be assigned
    def data=(data)
      if data.nil?
        fail ArgumentError, 'data cannot be nil'
      end

      @data = data
    end

    # Custom attribute writer method with validation
    # @param [Object] context Value to be assigned
    def context=(context)
      if context.nil?
        fail ArgumentError, 'context cannot be nil'
      end

      @context = context
    end

    # Custom attribute writer method with validation
    # @param [Object] chain_hash Value to be assigned
    def chain_hash=(chain_hash)
      if chain_hash.nil?
        fail ArgumentError, 'chain_hash cannot be nil'
      end

      @chain_hash = chain_hash
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          trail == o.trail &&
          event == o.event &&
          created_at == o.created_at &&
          received_at == o.received_at &&
          organization_id == o.organization_id &&
          actor == o.actor &&
          targets == o.targets &&
          metadata == o.metadata &&
          data == o.data &&
          context == o.context &&
          chain_hash == o.chain_hash &&
          schema_version == o.schema_version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, trail, event, created_at, received_at, organization_id, actor, targets, metadata, data, context, chain_hash, schema_version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
