=begin
#Santati

#Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SantatiCore
  class SchemaCheck < ApiModelBase
    # How many of the newest stored events were run.
    attr_accessor :checked

    # How many of them the document would reject.
    attr_accessor :failed

    # The first failing events, at most 50.
    attr_accessor :failures

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'checked' => :'checked',
        :'failed' => :'failed',
        :'failures' => :'failures'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'checked' => :'Integer',
        :'failed' => :'Integer',
        :'failures' => :'Array<SchemaCheckFailure>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SantatiCore::SchemaCheck` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SantatiCore::SchemaCheck`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'checked')
        self.checked = attributes[:'checked']
      else
        self.checked = nil
      end

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      else
        self.failed = nil
      end

      if attributes.key?(:'failures')
        if (value = attributes[:'failures']).is_a?(Array)
          self.failures = value
        end
      else
        self.failures = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @checked.nil?
        invalid_properties.push('invalid value for "checked", checked cannot be nil.')
      end

      if @failed.nil?
        invalid_properties.push('invalid value for "failed", failed cannot be nil.')
      end

      if @failures.nil?
        invalid_properties.push('invalid value for "failures", failures cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @checked.nil?
      return false if @failed.nil?
      return false if @failures.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] checked Value to be assigned
    def checked=(checked)
      if checked.nil?
        fail ArgumentError, 'checked cannot be nil'
      end

      @checked = checked
    end

    # Custom attribute writer method with validation
    # @param [Object] failed Value to be assigned
    def failed=(failed)
      if failed.nil?
        fail ArgumentError, 'failed cannot be nil'
      end

      @failed = failed
    end

    # Custom attribute writer method with validation
    # @param [Object] failures Value to be assigned
    def failures=(failures)
      if failures.nil?
        fail ArgumentError, 'failures cannot be nil'
      end

      @failures = failures
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          checked == o.checked &&
          failed == o.failed &&
          failures == o.failures
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [checked, failed, failures].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
