<?php
/**
 * EventIngestRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Santati\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Santati
 *
 * Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Santati\Core\Model;

use \ArrayAccess;
use \Santati\Core\ObjectSerializer;

/**
 * EventIngestRequest Class Doc Comment
 *
 * @category Class
 * @package  Santati\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EventIngestRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EventIngestRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'event' => 'string',
        'trail' => 'string',
        'created_at' => 'string',
        'organization_id' => 'string',
        'idempotency_key' => 'string',
        'actor' => '\Santati\Core\Model\EventActorRequest',
        'targets' => '\Santati\Core\Model\EventTargetRequest[]',
        'metadata' => 'array<string,string>',
        'data' => 'mixed',
        'context' => 'array<string,object>',
        'events' => '\Santati\Core\Model\EventEnvelopeRequest[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'event' => null,
        'trail' => null,
        'created_at' => null,
        'organization_id' => null,
        'idempotency_key' => null,
        'actor' => null,
        'targets' => null,
        'metadata' => null,
        'data' => null,
        'context' => null,
        'events' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'event' => false,
        'trail' => false,
        'created_at' => false,
        'organization_id' => false,
        'idempotency_key' => false,
        'actor' => false,
        'targets' => false,
        'metadata' => false,
        'data' => true,
        'context' => false,
        'events' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'event' => 'event',
        'trail' => 'trail',
        'created_at' => 'created_at',
        'organization_id' => 'organization_id',
        'idempotency_key' => 'idempotency_key',
        'actor' => 'actor',
        'targets' => 'targets',
        'metadata' => 'metadata',
        'data' => 'data',
        'context' => 'context',
        'events' => 'events'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'event' => 'setEvent',
        'trail' => 'setTrail',
        'created_at' => 'setCreatedAt',
        'organization_id' => 'setOrganizationId',
        'idempotency_key' => 'setIdempotencyKey',
        'actor' => 'setActor',
        'targets' => 'setTargets',
        'metadata' => 'setMetadata',
        'data' => 'setData',
        'context' => 'setContext',
        'events' => 'setEvents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'event' => 'getEvent',
        'trail' => 'getTrail',
        'created_at' => 'getCreatedAt',
        'organization_id' => 'getOrganizationId',
        'idempotency_key' => 'getIdempotencyKey',
        'actor' => 'getActor',
        'targets' => 'getTargets',
        'metadata' => 'getMetadata',
        'data' => 'getData',
        'context' => 'getContext',
        'events' => 'getEvents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('event', $data ?? [], null);
        $this->setIfExists('trail', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('idempotency_key', $data ?? [], null);
        $this->setIfExists('actor', $data ?? [], null);
        $this->setIfExists('targets', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('context', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['event'] === null) {
            $invalidProperties[] = "'event' can't be null";
        }
        if ((mb_strlen($this->container['event']) > 255)) {
            $invalidProperties[] = "invalid value for 'event', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['event']) < 1)) {
            $invalidProperties[] = "invalid value for 'event', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['trail'] === null) {
            $invalidProperties[] = "'trail' can't be null";
        }
        if ((mb_strlen($this->container['trail']) > 64)) {
            $invalidProperties[] = "invalid value for 'trail', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['trail']) < 1)) {
            $invalidProperties[] = "invalid value for 'trail', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['organization_id']) && (mb_strlen($this->container['organization_id']) > 255)) {
            $invalidProperties[] = "invalid value for 'organization_id', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['organization_id']) && (mb_strlen($this->container['organization_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'organization_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['idempotency_key']) && (mb_strlen($this->container['idempotency_key']) > 255)) {
            $invalidProperties[] = "invalid value for 'idempotency_key', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['idempotency_key']) && (mb_strlen($this->container['idempotency_key']) < 1)) {
            $invalidProperties[] = "invalid value for 'idempotency_key', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['events'] === null) {
            $invalidProperties[] = "'events' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event
     *
     * @return string
     */
    public function getEvent()
    {
        return $this->container['event'];
    }

    /**
     * Sets event
     *
     * @param string $event The event type, e.g. invoice.voided.
     *
     * @return self
     */
    public function setEvent($event)
    {
        if (is_null($event)) {
            throw new \InvalidArgumentException('non-nullable event cannot be null');
        }
        if ((mb_strlen($event) > 255)) {
            throw new \InvalidArgumentException('invalid length for $event when calling EventIngestRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($event) < 1)) {
            throw new \InvalidArgumentException('invalid length for $event when calling EventIngestRequest., must be bigger than or equal to 1.');
        }

        $this->container['event'] = $event;

        return $this;
    }

    /**
     * Gets trail
     *
     * @return string
     */
    public function getTrail()
    {
        return $this->container['trail'];
    }

    /**
     * Sets trail
     *
     * @param string $trail The audit log trail to index this event on; the key must be scoped to it.
     *
     * @return self
     */
    public function setTrail($trail)
    {
        if (is_null($trail)) {
            throw new \InvalidArgumentException('non-nullable trail cannot be null');
        }
        if ((mb_strlen($trail) > 64)) {
            throw new \InvalidArgumentException('invalid length for $trail when calling EventIngestRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($trail) < 1)) {
            throw new \InvalidArgumentException('invalid length for $trail when calling EventIngestRequest., must be bigger than or equal to 1.');
        }

        $this->container['trail'] = $trail;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at RFC 3339 with an offset: when the event happened. Defaults to receipt time; a timestamp without an offset is refused.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id The end-customer organization this event belongs to.
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        if ((mb_strlen($organization_id) > 255)) {
            throw new \InvalidArgumentException('invalid length for $organization_id when calling EventIngestRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($organization_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $organization_id when calling EventIngestRequest., must be bigger than or equal to 1.');
        }

        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets idempotency_key
     *
     * @return string|null
     */
    public function getIdempotencyKey()
    {
        return $this->container['idempotency_key'];
    }

    /**
     * Sets idempotency_key
     *
     * @param string|null $idempotency_key Replay guard, per trail: a repeat of the same key within 24 hours returns the event already stored instead of indexing a new one.
     *
     * @return self
     */
    public function setIdempotencyKey($idempotency_key)
    {
        if (is_null($idempotency_key)) {
            throw new \InvalidArgumentException('non-nullable idempotency_key cannot be null');
        }
        if ((mb_strlen($idempotency_key) > 255)) {
            throw new \InvalidArgumentException('invalid length for $idempotency_key when calling EventIngestRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($idempotency_key) < 1)) {
            throw new \InvalidArgumentException('invalid length for $idempotency_key when calling EventIngestRequest., must be bigger than or equal to 1.');
        }

        $this->container['idempotency_key'] = $idempotency_key;

        return $this;
    }

    /**
     * Gets actor
     *
     * @return \Santati\Core\Model\EventActorRequest|null
     */
    public function getActor()
    {
        return $this->container['actor'];
    }

    /**
     * Sets actor
     *
     * @param \Santati\Core\Model\EventActorRequest|null $actor Who acted; omit it for an event with no actor.
     *
     * @return self
     */
    public function setActor($actor)
    {
        if (is_null($actor)) {
            throw new \InvalidArgumentException('non-nullable actor cannot be null');
        }
        $this->container['actor'] = $actor;

        return $this;
    }

    /**
     * Gets targets
     *
     * @return \Santati\Core\Model\EventTargetRequest[]|null
     */
    public function getTargets()
    {
        return $this->container['targets'];
    }

    /**
     * Sets targets
     *
     * @param \Santati\Core\Model\EventTargetRequest[]|null $targets The objects the event acted on; at most 10.
     *
     * @return self
     */
    public function setTargets($targets)
    {
        if (is_null($targets)) {
            throw new \InvalidArgumentException('non-nullable targets cannot be null');
        }
        $this->container['targets'] = $targets;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Event metadata: at most 50 keys, each at most 40 characters of A-Z a-z 0-9 _ . -, each value at most 500 characters.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets data
     *
     * @return mixed|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param mixed|null $data The producer's own payload for the event, stored verbatim and never interpreted.
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            array_push($this->openAPINullablesSetToNull, 'data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets context
     *
     * @return array<string,object>|null
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param array<string,object>|null $context Extra producer context, stored verbatim; `context.actor` and `context.targets` are read as a fallback when the top-level members are absent.
     *
     * @return self
     */
    public function setContext($context)
    {
        if (is_null($context)) {
            throw new \InvalidArgumentException('non-nullable context cannot be null');
        }
        $this->container['context'] = $context;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \Santati\Core\Model\EventEnvelopeRequest[]
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \Santati\Core\Model\EventEnvelopeRequest[] $events One to 500 envelopes, indexed in order.
     *
     * @return self
     */
    public function setEvents($events)
    {
        if (is_null($events)) {
            throw new \InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


