/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EventActor } from './EventActor.js';
import {
    EventActorFromJSON,
    EventActorFromJSONTyped,
    EventActorToJSON,
    EventActorToJSONTyped,
} from './EventActor.js';
import type { EventTarget } from './EventTarget.js';
import {
    EventTargetFromJSON,
    EventTargetFromJSONTyped,
    EventTargetToJSON,
    EventTargetToJSONTyped,
} from './EventTarget.js';

/**
 * 
 * @export
 * @interface AuditEvent
 */
export interface AuditEvent {
    /**
     * The producer's event id, or a generated ULID when none was sent.
     */
    id: string;
    /**
     * The audit log trail the event was indexed on.
     */
    trail: string;
    /**
     * The event type, e.g. invoice.voided.
     */
    event: string;
    /**
     * RFC 3339, when the producer says the event happened.
     */
    createdAt: string;
    /**
     * RFC 3339, when Santati indexed the event.
     */
    receivedAt: string;
    /**
     * The end-customer organization the producer attributed the event to; empty when none.
     */
    organizationId?: string;
    /**
     * Who acted: the actor columns first, the producer's payload behind them.
     */
    actor: EventActor;
    /**
     * The objects this event acted on, in the producer's order.
     */
    targets: Array<EventTarget>;
    /**
     * The event's own key/value map; keys and values are strings on the wire.
     */
    metadata: { [key: string]: string; };
    /**
     * The producer's own payload for the event, stored verbatim.
     */
    data: { [key: string]: any; };
    /**
     * The producer's extra context, stored verbatim; the read path falls back to it for
     * `actor` and `targets` when the top-level members are absent.
     */
    context: { [key: string]: any; };
    /**
     * sha256 of this event's chain record; empty until the seal task has run.
     */
    hash: string;
    /**
     * The event schema version the event was validated against.
     */
    schemaVersion: number | null;
}

/**
 * Check if a given object implements the AuditEvent interface.
 */
export function instanceOfAuditEvent(value: object): value is AuditEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('trail' in value) || value['trail'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('receivedAt' in (value as Record<string, any>)) && !('received_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['receivedAt'] === undefined && (value as Record<string, any>)['received_at'] === undefined)) return false;
    if (!('actor' in value) || value['actor'] === undefined) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if ((!('schemaVersion' in (value as Record<string, any>)) && !('schema_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['schemaVersion'] === undefined && (value as Record<string, any>)['schema_version'] === undefined)) return false;
    return true;
}

export function AuditEventFromJSON(json: any): AuditEvent {
    return AuditEventFromJSONTyped(json, false);
}

export function AuditEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'trail': json['trail'],
        'event': json['event'],
        'createdAt': json['created_at'],
        'receivedAt': json['received_at'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'actor': EventActorFromJSON(json['actor']),
        'targets': ((json['targets'] as Array<any>).map(EventTargetFromJSON)),
        'metadata': json['metadata'],
        'data': json['data'],
        'context': json['context'],
        'hash': json['hash'],
        'schemaVersion': json['schema_version'],
    };
}

export function AuditEventToJSON(json: any): AuditEvent {
    return AuditEventToJSONTyped(json, false);
}

export function AuditEventToJSONTyped(value?: AuditEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'trail': value['trail'],
        'event': value['event'],
        'created_at': value['createdAt'],
        'received_at': value['receivedAt'],
        'organization_id': value['organizationId'],
        'actor': EventActorToJSON(value['actor']),
        'targets': ((value['targets'] as Array<any>).map(EventTargetToJSON)),
        'metadata': value['metadata'],
        'data': value['data'],
        'context': value['context'],
        'hash': value['hash'],
        'schema_version': value['schemaVersion'],
    };
}

