/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EventBatchItemResult } from './EventBatchItemResult.js';
import {
    EventBatchItemResultFromJSON,
    EventBatchItemResultFromJSONTyped,
    EventBatchItemResultToJSON,
    EventBatchItemResultToJSONTyped,
} from './EventBatchItemResult.js';

/**
 * Documentation-only shape of a batch ingest response.
 * 
 * Mirrors `apps.audit_trails.api_views._batch_response`: one entry per submitted
 * event, in submission order, an accepted or duplicate entry carrying the stored
 * event's id and a rejected entry carrying the error envelope instead. The
 * response is 202 when nothing was rejected and 207 when anything was.
 * @export
 * @interface EventBatchResult
 */
export interface EventBatchResult {
    /**
     * How many events this request indexed (including idempotent replays).
     */
    accepted: number;
    /**
     * How many events this request rejected.
     */
    rejected: number;
    /**
     * One result per submitted event, in submission order.
     */
    results: Array<EventBatchItemResult>;
}

/**
 * Check if a given object implements the EventBatchResult interface.
 */
export function instanceOfEventBatchResult(value: object): value is EventBatchResult {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('rejected' in value) || value['rejected'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function EventBatchResultFromJSON(json: any): EventBatchResult {
    return EventBatchResultFromJSONTyped(json, false);
}

export function EventBatchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventBatchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'rejected': json['rejected'],
        'results': ((json['results'] as Array<any>).map(EventBatchItemResultFromJSON)),
    };
}

export function EventBatchResultToJSON(json: any): EventBatchResult {
    return EventBatchResultToJSONTyped(json, false);
}

export function EventBatchResultToJSONTyped(value?: EventBatchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'rejected': value['rejected'],
        'results': ((value['results'] as Array<any>).map(EventBatchItemResultToJSON)),
    };
}

