/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EventDefinition
 */
export interface EventDefinition {
    /**
     * The action name, e.g. invoice.voided.
     */
    action: string;
    /**
     * What this action means, for the people reading the catalog.
     */
    description: string;
    /**
     * Target types an event with this action may name; empty means any target type.
     */
    allowedTargetTypes: Array<string>;
    /**
     * True while the action is in force. A definition that is not active is treated as undefined when a team has any definitions at all.
     */
    isActive: boolean;
    /**
     * When the action was first defined.
     */
    createdAt: string;
    /**
     * When the definition was last changed.
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the EventDefinition interface.
 */
export function instanceOfEventDefinition(value: object): value is EventDefinition {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('allowedTargetTypes' in (value as Record<string, any>)) && !('allowed_target_types' in (value as Record<string, any>))) || ((value as Record<string, any>)['allowedTargetTypes'] === undefined && (value as Record<string, any>)['allowed_target_types'] === undefined)) return false;
    if ((!('isActive' in (value as Record<string, any>)) && !('is_active' in (value as Record<string, any>))) || ((value as Record<string, any>)['isActive'] === undefined && (value as Record<string, any>)['is_active'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function EventDefinitionFromJSON(json: any): EventDefinition {
    return EventDefinitionFromJSONTyped(json, false);
}

export function EventDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'description': json['description'],
        'allowedTargetTypes': json['allowed_target_types'],
        'isActive': json['is_active'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function EventDefinitionToJSON(json: any): EventDefinition {
    return EventDefinitionToJSONTyped(json, false);
}

export function EventDefinitionToJSONTyped(value?: EventDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'description': value['description'],
        'allowed_target_types': value['allowedTargetTypes'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

