/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { EventBatchRequest } from './EventBatchRequest.js';
import {
    instanceOfEventBatchRequest,
    EventBatchRequestFromJSON,
    EventBatchRequestFromJSONTyped,
    EventBatchRequestToJSON,
} from './EventBatchRequest.js';
import type { EventEnvelopeRequest } from './EventEnvelopeRequest.js';
import {
    instanceOfEventEnvelopeRequest,
    EventEnvelopeRequestFromJSON,
    EventEnvelopeRequestFromJSONTyped,
    EventEnvelopeRequestToJSON,
} from './EventEnvelopeRequest.js';

/**
 * @type EventIngestRequest
 * 
 * @export
 */
export type EventIngestRequest = EventBatchRequest | EventEnvelopeRequest;

export function EventIngestRequestFromJSON(json: any): EventIngestRequest {
    return EventIngestRequestFromJSONTyped(json, false);
}

export function EventIngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventIngestRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEventBatchRequest(json)) {
        return EventBatchRequestFromJSONTyped(json, true);
    }
    if (instanceOfEventEnvelopeRequest(json)) {
        return EventEnvelopeRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function EventIngestRequestToJSON(json: any): any {
    return EventIngestRequestToJSONTyped(json, false);
}

export function EventIngestRequestToJSONTyped(value?: EventIngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEventBatchRequest(value)) {
        return EventBatchRequestToJSON(value as EventBatchRequest);
    }
    if (instanceOfEventEnvelopeRequest(value)) {
        return EventEnvelopeRequestToJSON(value as EventEnvelopeRequest);
    }
    return {};
}

