/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OcsfMapping
 */
export interface OcsfMapping {
    /**
     * The OCSF release the mapping targets, e.g. 1.9.0.
     */
    version: string;
    /**
     * The OCSF class the action maps to.
     */
    classUid: number;
    /**
     * The class's activity_id enum value; 99 is Other, a best fit rather than exact.
     */
    activityId: number;
    /**
     * The OCSF status_id the outcome sets: 2 for a failure, null when the action sets none.
     */
    statusId: number | null;
}

/**
 * Check if a given object implements the OcsfMapping interface.
 */
export function instanceOfOcsfMapping(value: object): value is OcsfMapping {
    if (!('version' in value) || value['version'] === undefined) return false;
    if ((!('classUid' in (value as Record<string, any>)) && !('class_uid' in (value as Record<string, any>))) || ((value as Record<string, any>)['classUid'] === undefined && (value as Record<string, any>)['class_uid'] === undefined)) return false;
    if ((!('activityId' in (value as Record<string, any>)) && !('activity_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['activityId'] === undefined && (value as Record<string, any>)['activity_id'] === undefined)) return false;
    if ((!('statusId' in (value as Record<string, any>)) && !('status_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['statusId'] === undefined && (value as Record<string, any>)['status_id'] === undefined)) return false;
    return true;
}

export function OcsfMappingFromJSON(json: any): OcsfMapping {
    return OcsfMappingFromJSONTyped(json, false);
}

export function OcsfMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): OcsfMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'classUid': json['class_uid'],
        'activityId': json['activity_id'],
        'statusId': json['status_id'],
    };
}

export function OcsfMappingToJSON(json: any): OcsfMapping {
    return OcsfMappingToJSONTyped(json, false);
}

export function OcsfMappingToJSONTyped(value?: OcsfMapping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'class_uid': value['classUid'],
        'activity_id': value['activityId'],
        'status_id': value['statusId'],
    };
}

