/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AuditEvent } from './AuditEvent.js';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent.js';

/**
 * 
 * @export
 * @interface PaginatedAuditEventList
 */
export interface PaginatedAuditEventList {
    /**
     * URL of the next page of results, or null on the last page.
     */
    next?: string | null;
    /**
     * URL of the previous page of results, or null on the first page.
     */
    previous?: string | null;
    /**
     * 
     */
    results: Array<AuditEvent>;
}

/**
 * Check if a given object implements the PaginatedAuditEventList interface.
 */
export function instanceOfPaginatedAuditEventList(value: object): value is PaginatedAuditEventList {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAuditEventListFromJSON(json: any): PaginatedAuditEventList {
    return PaginatedAuditEventListFromJSONTyped(json, false);
}

export function PaginatedAuditEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAuditEventList {
    if (json == null) {
        return json;
    }
    return {
        
        'next': json['next'] === undefined ? undefined : json['next'] === null ? null : json['next'],
        'previous': json['previous'] === undefined ? undefined : json['previous'] === null ? null : json['previous'],
        'results': ((json['results'] as Array<any>).map(AuditEventFromJSON)),
    };
}

export function PaginatedAuditEventListToJSON(json: any): PaginatedAuditEventList {
    return PaginatedAuditEventListToJSONTyped(json, false);
}

export function PaginatedAuditEventListToJSONTyped(value?: PaginatedAuditEventList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AuditEventToJSON)),
    };
}

