/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * The writable part of a definition, for create and (partially) for update.
 * @export
 * @interface PatchedEventDefinitionWriteRequest
 */
export interface PatchedEventDefinitionWriteRequest {
    /**
     * The action name, e.g. invoice.voided: dotted segments of letters, digits, '-' and '_'. Sending a new value on an update renames the action; its schema versions go with it.
     */
    action?: string;
    /**
     * What this action means, for the people reading the catalog.
     */
    description?: string;
    /**
     * Target types an event with this action may name; empty means any target type.
     */
    allowedTargetTypes?: Array<string>;
    /**
     * True while the action is in force. A definition that is not active is treated as undefined when a team has any definitions at all.
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the PatchedEventDefinitionWriteRequest interface.
 */
export function instanceOfPatchedEventDefinitionWriteRequest(value: object): value is PatchedEventDefinitionWriteRequest {
    return true;
}

export function PatchedEventDefinitionWriteRequestFromJSON(json: any): PatchedEventDefinitionWriteRequest {
    return PatchedEventDefinitionWriteRequestFromJSONTyped(json, false);
}

export function PatchedEventDefinitionWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEventDefinitionWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'description': json['description'] == null ? undefined : json['description'],
        'allowedTargetTypes': json['allowed_target_types'] == null ? undefined : json['allowed_target_types'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function PatchedEventDefinitionWriteRequestToJSON(json: any): PatchedEventDefinitionWriteRequest {
    return PatchedEventDefinitionWriteRequestToJSONTyped(json, false);
}

export function PatchedEventDefinitionWriteRequestToJSONTyped(value?: PatchedEventDefinitionWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'description': value['description'],
        'allowed_target_types': value['allowedTargetTypes'],
        'is_active': value['isActive'],
    };
}

