/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SchemaCheckFailure
 */
export interface SchemaCheckFailure {
    /**
     * The stored event that fails the document.
     */
    eventId: string;
    /**
     * When the event occurred.
     */
    occurredAt: string;
    /**
     * The dotted path of the offending value, or null for the root.
     */
    field: string | null;
    /**
     * What the document rejected.
     */
    message: string;
}

/**
 * Check if a given object implements the SchemaCheckFailure interface.
 */
export function instanceOfSchemaCheckFailure(value: object): value is SchemaCheckFailure {
    if ((!('eventId' in (value as Record<string, any>)) && !('event_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventId'] === undefined && (value as Record<string, any>)['event_id'] === undefined)) return false;
    if ((!('occurredAt' in (value as Record<string, any>)) && !('occurred_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['occurredAt'] === undefined && (value as Record<string, any>)['occurred_at'] === undefined)) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SchemaCheckFailureFromJSON(json: any): SchemaCheckFailure {
    return SchemaCheckFailureFromJSONTyped(json, false);
}

export function SchemaCheckFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaCheckFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'occurredAt': json['occurred_at'],
        'field': json['field'],
        'message': json['message'],
    };
}

export function SchemaCheckFailureToJSON(json: any): SchemaCheckFailure {
    return SchemaCheckFailureToJSONTyped(json, false);
}

export function SchemaCheckFailureToJSONTyped(value?: SchemaCheckFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'occurred_at': value['occurredAt'],
        'field': value['field'],
        'message': value['message'],
    };
}

