/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SchemaCheckFailure } from './SchemaCheckFailure.js';
import {
    SchemaCheckFailureFromJSON,
    SchemaCheckFailureFromJSONTyped,
    SchemaCheckFailureToJSON,
    SchemaCheckFailureToJSONTyped,
} from './SchemaCheckFailure.js';

/**
 * 
 * @export
 * @interface SchemaCheck
 */
export interface SchemaCheck {
    /**
     * How many of the newest stored events were run.
     */
    checked: number;
    /**
     * How many of them the document would reject.
     */
    failed: number;
    /**
     * The first failing events, at most 50.
     */
    failures: Array<SchemaCheckFailure>;
}

/**
 * Check if a given object implements the SchemaCheck interface.
 */
export function instanceOfSchemaCheck(value: object): value is SchemaCheck {
    if (!('checked' in value) || value['checked'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    return true;
}

export function SchemaCheckFromJSON(json: any): SchemaCheck {
    return SchemaCheckFromJSONTyped(json, false);
}

export function SchemaCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'checked': json['checked'],
        'failed': json['failed'],
        'failures': ((json['failures'] as Array<any>).map(SchemaCheckFailureFromJSON)),
    };
}

export function SchemaCheckToJSON(json: any): SchemaCheck {
    return SchemaCheckToJSONTyped(json, false);
}

export function SchemaCheckToJSONTyped(value?: SchemaCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checked': value['checked'],
        'failed': value['failed'],
        'failures': ((value['failures'] as Array<any>).map(SchemaCheckFailureToJSON)),
    };
}

