/* tslint:disable */
/* eslint-disable */
/**
 * Santati
 * Santati\'s HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StandardPackInstallResult
 */
export interface StandardPackInstallResult {
    /**
     * Actions defined now, each with a published v1.
     */
    created: Array<string>;
    /**
     * Actions the team already defined; they are left untouched.
     */
    skipped: Array<string>;
}

/**
 * Check if a given object implements the StandardPackInstallResult interface.
 */
export function instanceOfStandardPackInstallResult(value: object): value is StandardPackInstallResult {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    return true;
}

export function StandardPackInstallResultFromJSON(json: any): StandardPackInstallResult {
    return StandardPackInstallResultFromJSONTyped(json, false);
}

export function StandardPackInstallResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandardPackInstallResult {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'skipped': json['skipped'],
    };
}

export function StandardPackInstallResultToJSON(json: any): StandardPackInstallResult {
    return StandardPackInstallResultToJSONTyped(json, false);
}

export function StandardPackInstallResultToJSONTyped(value?: StandardPackInstallResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'skipped': value['skipped'],
    };
}

