# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.EventDefinition do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :action,
    :description,
    :allowed_target_types,
    :is_active,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :action => String.t,
    :description => String.t,
    :allowed_target_types => [String.t],
    :is_active => boolean(),
    :created_at => String.t,
    :updated_at => String.t
  }

  def decode(value) do
    value
  end
end

