# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.EventBatchRequest do
  @moduledoc """
  Documentation-only shape of a batch ingest request: ``{\"events\": [...]}``.  One request may carry at most `MAX_EVENTS_PER_BATCH` envelopes; the whole body is capped at 1 MiB.
  """

  @derive JSON.Encoder
  defstruct [
    :events
  ]

  @type t :: %__MODULE__{
    :events => [SantatiCore.Model.EventEnvelopeRequest.t]
  }

  alias SantatiCore.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:events, :list, SantatiCore.Model.EventEnvelopeRequest)
  end
end

