# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.EventActor do
  @moduledoc """
  Who acted, in the producer's own ids.  Documentation-only on the write path — `apps.audit_trails.ingest` is the validator — and the shape `AuditEventSerializer.get_actor` always returns, so every key is present on a read even when the producer sent none of them.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :id,
    :name,
    :metadata
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t | nil,
    :name => String.t | nil,
    :metadata => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

