# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.PaginatedEventSchemaVersionList do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :next,
    :previous,
    :results
  ]

  @type t :: %__MODULE__{
    :next => String.t | nil,
    :previous => String.t | nil,
    :results => [SantatiCore.Model.EventSchemaVersion.t]
  }

  alias SantatiCore.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:results, :list, SantatiCore.Model.EventSchemaVersion)
  end
end

