# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.SchemaCheckFailure do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :event_id,
    :occurred_at,
    :field,
    :message
  ]

  @type t :: %__MODULE__{
    :event_id => String.t,
    :occurred_at => String.t,
    :field => String.t | nil,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

