# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.SchemaCheck do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :checked,
    :failed,
    :failures
  ]

  @type t :: %__MODULE__{
    :checked => integer(),
    :failed => integer(),
    :failures => [SantatiCore.Model.SchemaCheckFailure.t]
  }

  alias SantatiCore.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:failures, :list, SantatiCore.Model.SchemaCheckFailure)
  end
end

