# NOTE: This file is auto generated by OpenAPI Generator 7.25.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SantatiCore.Model.StandardPackInstallRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :packs
  ]

  @type t :: %__MODULE__{
    :packs => [String.t]
  }

  def decode(value) do
    value
  end
end

