/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the EventSchemaVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSchemaVersion{}

// EventSchemaVersion struct for EventSchemaVersion
type EventSchemaVersion struct {
	// The per-action version number; never reused, even after a draft is deleted.
	Version int32 `json:"version"`
	// draft: editable, validates nothing. published: immutable, validates ingest. deprecated: a newer version superseded it; pinned producers are accepted until `deprecation_deadline`.  * `draft` - Draft * `published` - Published * `deprecated` - Deprecated
	Status string `json:"status"`
	// The JSON Schema 2020-12 document. It validates the event's `metadata`, `actor.metadata` and each `targets[].metadata`; metadata values are always strings.
	Schema map[string]interface{} `json:"schema"`
	// When the version was published; null for a draft.
	PublishedAt NullableString `json:"published_at"`
	// When a newer version superseded this one; null until then.
	DeprecatedAt NullableString `json:"deprecated_at"`
	// When a deprecated version stops accepting pinned traffic; null while it is not deprecated.
	DeprecationDeadline NullableString `json:"deprecation_deadline"`
	// When the draft was first created.
	CreatedAt string `json:"created_at"`
	// When the version last changed. The `ETag` tracks it.
	UpdatedAt string `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _EventSchemaVersion EventSchemaVersion

// NewEventSchemaVersion instantiates a new EventSchemaVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSchemaVersion(version int32, status string, schema map[string]interface{}, publishedAt NullableString, deprecatedAt NullableString, deprecationDeadline NullableString, createdAt string, updatedAt string) *EventSchemaVersion {
	this := EventSchemaVersion{}
	this.Version = version
	this.Status = status
	this.Schema = schema
	this.PublishedAt = publishedAt
	this.DeprecatedAt = deprecatedAt
	this.DeprecationDeadline = deprecationDeadline
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEventSchemaVersionWithDefaults instantiates a new EventSchemaVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSchemaVersionWithDefaults() *EventSchemaVersion {
	this := EventSchemaVersion{}
	return &this
}

// GetVersion returns the Version field value
func (o *EventSchemaVersion) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *EventSchemaVersion) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *EventSchemaVersion) SetVersion(v int32) {
	o.Version = v
}

// GetStatus returns the Status field value
func (o *EventSchemaVersion) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EventSchemaVersion) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EventSchemaVersion) SetStatus(v string) {
	o.Status = v
}

// GetSchema returns the Schema field value
func (o *EventSchemaVersion) GetSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *EventSchemaVersion) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// SetSchema sets field value
func (o *EventSchemaVersion) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetPublishedAt returns the PublishedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EventSchemaVersion) GetPublishedAt() string {
	if o == nil || o.PublishedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.PublishedAt.Get()
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventSchemaVersion) GetPublishedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublishedAt.Get(), o.PublishedAt.IsSet()
}

// SetPublishedAt sets field value
func (o *EventSchemaVersion) SetPublishedAt(v string) {
	o.PublishedAt.Set(&v)
}

// GetDeprecatedAt returns the DeprecatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EventSchemaVersion) GetDeprecatedAt() string {
	if o == nil || o.DeprecatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeprecatedAt.Get()
}

// GetDeprecatedAtOk returns a tuple with the DeprecatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventSchemaVersion) GetDeprecatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeprecatedAt.Get(), o.DeprecatedAt.IsSet()
}

// SetDeprecatedAt sets field value
func (o *EventSchemaVersion) SetDeprecatedAt(v string) {
	o.DeprecatedAt.Set(&v)
}

// GetDeprecationDeadline returns the DeprecationDeadline field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EventSchemaVersion) GetDeprecationDeadline() string {
	if o == nil || o.DeprecationDeadline.Get() == nil {
		var ret string
		return ret
	}

	return *o.DeprecationDeadline.Get()
}

// GetDeprecationDeadlineOk returns a tuple with the DeprecationDeadline field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EventSchemaVersion) GetDeprecationDeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeprecationDeadline.Get(), o.DeprecationDeadline.IsSet()
}

// SetDeprecationDeadline sets field value
func (o *EventSchemaVersion) SetDeprecationDeadline(v string) {
	o.DeprecationDeadline.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *EventSchemaVersion) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EventSchemaVersion) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EventSchemaVersion) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EventSchemaVersion) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EventSchemaVersion) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EventSchemaVersion) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o EventSchemaVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSchemaVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["status"] = o.Status
	toSerialize["schema"] = o.Schema
	toSerialize["published_at"] = o.PublishedAt.Get()
	toSerialize["deprecated_at"] = o.DeprecatedAt.Get()
	toSerialize["deprecation_deadline"] = o.DeprecationDeadline.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventSchemaVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"status",
		"schema",
		"published_at",
		"deprecated_at",
		"deprecation_deadline",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSchemaVersion := _EventSchemaVersion{}

	err = json.Unmarshal(data, &varEventSchemaVersion)

	if err != nil {
		return err
	}

	*o = EventSchemaVersion(varEventSchemaVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "status")
		delete(additionalProperties, "schema")
		delete(additionalProperties, "published_at")
		delete(additionalProperties, "deprecated_at")
		delete(additionalProperties, "deprecation_deadline")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventSchemaVersion struct {
	value *EventSchemaVersion
	isSet bool
}

func (v NullableEventSchemaVersion) Get() *EventSchemaVersion {
	return v.value
}

func (v *NullableEventSchemaVersion) Set(val *EventSchemaVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSchemaVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSchemaVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSchemaVersion(val *EventSchemaVersion) *NullableEventSchemaVersion {
	return &NullableEventSchemaVersion{value: val, isSet: true}
}

func (v NullableEventSchemaVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSchemaVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


