/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the StandardEventCatalog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardEventCatalog{}

// StandardEventCatalog struct for StandardEventCatalog
type StandardEventCatalog struct {
	// Every standard pack.
	Packs []StandardPack `json:"packs"`
	AdditionalProperties map[string]interface{}
}

type _StandardEventCatalog StandardEventCatalog

// NewStandardEventCatalog instantiates a new StandardEventCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardEventCatalog(packs []StandardPack) *StandardEventCatalog {
	this := StandardEventCatalog{}
	this.Packs = packs
	return &this
}

// NewStandardEventCatalogWithDefaults instantiates a new StandardEventCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardEventCatalogWithDefaults() *StandardEventCatalog {
	this := StandardEventCatalog{}
	return &this
}

// GetPacks returns the Packs field value
func (o *StandardEventCatalog) GetPacks() []StandardPack {
	if o == nil {
		var ret []StandardPack
		return ret
	}

	return o.Packs
}

// GetPacksOk returns a tuple with the Packs field value
// and a boolean to check if the value has been set.
func (o *StandardEventCatalog) GetPacksOk() ([]StandardPack, bool) {
	if o == nil {
		return nil, false
	}
	return o.Packs, true
}

// SetPacks sets field value
func (o *StandardEventCatalog) SetPacks(v []StandardPack) {
	o.Packs = v
}

func (o StandardEventCatalog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardEventCatalog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["packs"] = o.Packs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StandardEventCatalog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"packs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardEventCatalog := _StandardEventCatalog{}

	err = json.Unmarshal(data, &varStandardEventCatalog)

	if err != nil {
		return err
	}

	*o = StandardEventCatalog(varStandardEventCatalog)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "packs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStandardEventCatalog struct {
	value *StandardEventCatalog
	isSet bool
}

func (v NullableStandardEventCatalog) Get() *StandardEventCatalog {
	return v.value
}

func (v *NullableStandardEventCatalog) Set(val *StandardEventCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardEventCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardEventCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardEventCatalog(val *StandardEventCatalog) *NullableStandardEventCatalog {
	return &NullableStandardEventCatalog{value: val, isSet: true}
}

func (v NullableStandardEventCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardEventCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


