/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the EventSchemaDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSchemaDocumentRequest{}

// EventSchemaDocumentRequest A schema document: the body of a draft create or update, and of a dry run.
type EventSchemaDocumentRequest struct {
	// The whole JSON Schema 2020-12 document, as a JSON object. Every `$ref` must point inside it (`#...`).
	Schema map[string]interface{} `json:"schema"`
	AdditionalProperties map[string]interface{}
}

type _EventSchemaDocumentRequest EventSchemaDocumentRequest

// NewEventSchemaDocumentRequest instantiates a new EventSchemaDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSchemaDocumentRequest(schema map[string]interface{}) *EventSchemaDocumentRequest {
	this := EventSchemaDocumentRequest{}
	this.Schema = schema
	return &this
}

// NewEventSchemaDocumentRequestWithDefaults instantiates a new EventSchemaDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSchemaDocumentRequestWithDefaults() *EventSchemaDocumentRequest {
	this := EventSchemaDocumentRequest{}
	return &this
}

// GetSchema returns the Schema field value
func (o *EventSchemaDocumentRequest) GetSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *EventSchemaDocumentRequest) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// SetSchema sets field value
func (o *EventSchemaDocumentRequest) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

func (o EventSchemaDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSchemaDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schema"] = o.Schema

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventSchemaDocumentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schema",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSchemaDocumentRequest := _EventSchemaDocumentRequest{}

	err = json.Unmarshal(data, &varEventSchemaDocumentRequest)

	if err != nil {
		return err
	}

	*o = EventSchemaDocumentRequest(varEventSchemaDocumentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schema")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventSchemaDocumentRequest struct {
	value *EventSchemaDocumentRequest
	isSet bool
}

func (v NullableEventSchemaDocumentRequest) Get() *EventSchemaDocumentRequest {
	return v.value
}

func (v *NullableEventSchemaDocumentRequest) Set(val *EventSchemaDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSchemaDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSchemaDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSchemaDocumentRequest(val *EventSchemaDocumentRequest) *NullableEventSchemaDocumentRequest {
	return &NullableEventSchemaDocumentRequest{value: val, isSet: true}
}

func (v NullableEventSchemaDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSchemaDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


