/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the StandardEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardEvent{}

// StandardEvent struct for StandardEvent
type StandardEvent struct {
	// The action name, e.g. agent.tool.called.
	Action string `json:"action"`
	// What the action means.
	Description string `json:"description"`
	// Target types installed as the action's allowed target types; empty means any.
	TargetTypes []string `json:"target_types"`
	// Metadata keys every event with this action must carry.
	RequiredMetadata []string `json:"required_metadata"`
	// Metadata keys the schema declares as strings but does not require.
	OptionalMetadata []string `json:"optional_metadata"`
	// The JSON Schema 2020-12 document installed as the action's published v1.
	Schema map[string]interface{} `json:"schema"`
	// The action's OCSF class and activity.
	Ocsf OcsfMapping `json:"ocsf"`
	AdditionalProperties map[string]interface{}
}

type _StandardEvent StandardEvent

// NewStandardEvent instantiates a new StandardEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardEvent(action string, description string, targetTypes []string, requiredMetadata []string, optionalMetadata []string, schema map[string]interface{}, ocsf OcsfMapping) *StandardEvent {
	this := StandardEvent{}
	this.Action = action
	this.Description = description
	this.TargetTypes = targetTypes
	this.RequiredMetadata = requiredMetadata
	this.OptionalMetadata = optionalMetadata
	this.Schema = schema
	this.Ocsf = ocsf
	return &this
}

// NewStandardEventWithDefaults instantiates a new StandardEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardEventWithDefaults() *StandardEvent {
	this := StandardEvent{}
	return &this
}

// GetAction returns the Action field value
func (o *StandardEvent) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *StandardEvent) SetAction(v string) {
	o.Action = v
}

// GetDescription returns the Description field value
func (o *StandardEvent) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *StandardEvent) SetDescription(v string) {
	o.Description = v
}

// GetTargetTypes returns the TargetTypes field value
func (o *StandardEvent) GetTargetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TargetTypes
}

// GetTargetTypesOk returns a tuple with the TargetTypes field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetTargetTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetTypes, true
}

// SetTargetTypes sets field value
func (o *StandardEvent) SetTargetTypes(v []string) {
	o.TargetTypes = v
}

// GetRequiredMetadata returns the RequiredMetadata field value
func (o *StandardEvent) GetRequiredMetadata() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RequiredMetadata
}

// GetRequiredMetadataOk returns a tuple with the RequiredMetadata field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetRequiredMetadataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredMetadata, true
}

// SetRequiredMetadata sets field value
func (o *StandardEvent) SetRequiredMetadata(v []string) {
	o.RequiredMetadata = v
}

// GetOptionalMetadata returns the OptionalMetadata field value
func (o *StandardEvent) GetOptionalMetadata() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OptionalMetadata
}

// GetOptionalMetadataOk returns a tuple with the OptionalMetadata field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetOptionalMetadataOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OptionalMetadata, true
}

// SetOptionalMetadata sets field value
func (o *StandardEvent) SetOptionalMetadata(v []string) {
	o.OptionalMetadata = v
}

// GetSchema returns the Schema field value
func (o *StandardEvent) GetSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// SetSchema sets field value
func (o *StandardEvent) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetOcsf returns the Ocsf field value
func (o *StandardEvent) GetOcsf() OcsfMapping {
	if o == nil {
		var ret OcsfMapping
		return ret
	}

	return o.Ocsf
}

// GetOcsfOk returns a tuple with the Ocsf field value
// and a boolean to check if the value has been set.
func (o *StandardEvent) GetOcsfOk() (*OcsfMapping, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ocsf, true
}

// SetOcsf sets field value
func (o *StandardEvent) SetOcsf(v OcsfMapping) {
	o.Ocsf = v
}

func (o StandardEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["description"] = o.Description
	toSerialize["target_types"] = o.TargetTypes
	toSerialize["required_metadata"] = o.RequiredMetadata
	toSerialize["optional_metadata"] = o.OptionalMetadata
	toSerialize["schema"] = o.Schema
	toSerialize["ocsf"] = o.Ocsf

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StandardEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"description",
		"target_types",
		"required_metadata",
		"optional_metadata",
		"schema",
		"ocsf",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardEvent := _StandardEvent{}

	err = json.Unmarshal(data, &varStandardEvent)

	if err != nil {
		return err
	}

	*o = StandardEvent(varStandardEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "description")
		delete(additionalProperties, "target_types")
		delete(additionalProperties, "required_metadata")
		delete(additionalProperties, "optional_metadata")
		delete(additionalProperties, "schema")
		delete(additionalProperties, "ocsf")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStandardEvent struct {
	value *StandardEvent
	isSet bool
}

func (v NullableStandardEvent) Get() *StandardEvent {
	return v.value
}

func (v *NullableStandardEvent) Set(val *StandardEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardEvent(val *StandardEvent) *NullableStandardEvent {
	return &NullableStandardEvent{value: val, isSet: true}
}

func (v NullableStandardEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


