/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the StandardPack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardPack{}

// StandardPack struct for StandardPack
type StandardPack struct {
	// Stable identifier of the pack.
	Slug string `json:"slug"`
	// Display name of the pack.
	Name string `json:"name"`
	// What the pack covers.
	Description string `json:"description"`
	// The pack's actions.
	Events []StandardEvent `json:"events"`
	AdditionalProperties map[string]interface{}
}

type _StandardPack StandardPack

// NewStandardPack instantiates a new StandardPack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardPack(slug string, name string, description string, events []StandardEvent) *StandardPack {
	this := StandardPack{}
	this.Slug = slug
	this.Name = name
	this.Description = description
	this.Events = events
	return &this
}

// NewStandardPackWithDefaults instantiates a new StandardPack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardPackWithDefaults() *StandardPack {
	this := StandardPack{}
	return &this
}

// GetSlug returns the Slug field value
func (o *StandardPack) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *StandardPack) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *StandardPack) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *StandardPack) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StandardPack) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StandardPack) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *StandardPack) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *StandardPack) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *StandardPack) SetDescription(v string) {
	o.Description = v
}

// GetEvents returns the Events field value
func (o *StandardPack) GetEvents() []StandardEvent {
	if o == nil {
		var ret []StandardEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *StandardPack) GetEventsOk() ([]StandardEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *StandardPack) SetEvents(v []StandardEvent) {
	o.Events = v
}

func (o StandardPack) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardPack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["events"] = o.Events

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StandardPack) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"name",
		"description",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardPack := _StandardPack{}

	err = json.Unmarshal(data, &varStandardPack)

	if err != nil {
		return err
	}

	*o = StandardPack(varStandardPack)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slug")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStandardPack struct {
	value *StandardPack
	isSet bool
}

func (v NullableStandardPack) Get() *StandardPack {
	return v.value
}

func (v *NullableStandardPack) Set(val *StandardPack) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardPack) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardPack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardPack(val *StandardPack) *NullableStandardPack {
	return &NullableStandardPack{value: val, isSet: true}
}

func (v NullableStandardPack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardPack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


