/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the ErrorBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorBody{}

// ErrorBody One rejection, in the shape contracts §7 reserves for event ingestion.
type ErrorBody struct {
	// Reserved failure code, one of: `invalid_envelope`, `unknown_field`, `invalid_actor_type`, `metadata_limit_exceeded`, `too_many_targets`, `unknown_action`, `schema_validation_failed`, `unknown_organization`, `quota_exceeded`, `rate_limited`, `trail_not_allowed`, `payload_too_large`. New codes are additive.
	Code string `json:"code"`
	// Human-readable explanation of this particular failure.
	Message string `json:"message"`
	// The request field at fault, or null when no single field is.
	Field NullableString `json:"field"`
	AdditionalProperties map[string]interface{}
}

type _ErrorBody ErrorBody

// NewErrorBody instantiates a new ErrorBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorBody(code string, message string, field NullableString) *ErrorBody {
	this := ErrorBody{}
	this.Code = code
	this.Message = message
	this.Field = field
	return &this
}

// NewErrorBodyWithDefaults instantiates a new ErrorBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorBodyWithDefaults() *ErrorBody {
	this := ErrorBody{}
	return &this
}

// GetCode returns the Code field value
func (o *ErrorBody) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ErrorBody) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *ErrorBody) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ErrorBody) SetMessage(v string) {
	o.Message = v
}

// GetField returns the Field field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ErrorBody) GetField() string {
	if o == nil || o.Field.Get() == nil {
		var ret string
		return ret
	}

	return *o.Field.Get()
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ErrorBody) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Field.Get(), o.Field.IsSet()
}

// SetField sets field value
func (o *ErrorBody) SetField(v string) {
	o.Field.Set(&v)
}

func (o ErrorBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["field"] = o.Field.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ErrorBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorBody := _ErrorBody{}

	err = json.Unmarshal(data, &varErrorBody)

	if err != nil {
		return err
	}

	*o = ErrorBody(varErrorBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		delete(additionalProperties, "field")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableErrorBody struct {
	value *ErrorBody
	isSet bool
}

func (v NullableErrorBody) Get() *ErrorBody {
	return v.value
}

func (v *NullableErrorBody) Set(val *ErrorBody) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorBody) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorBody(val *ErrorBody) *NullableErrorBody {
	return &NullableErrorBody{value: val, isSet: true}
}

func (v NullableErrorBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


