/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the EventBatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventBatchRequest{}

// EventBatchRequest Documentation-only shape of a batch ingest request: ``{\"events\": [...]}``.  One request may carry at most `MAX_EVENTS_PER_BATCH` envelopes; the whole body is capped at 1 MiB.
type EventBatchRequest struct {
	// One to 500 envelopes, indexed in order.
	Events []EventEnvelopeRequest `json:"events"`
	AdditionalProperties map[string]interface{}
}

type _EventBatchRequest EventBatchRequest

// NewEventBatchRequest instantiates a new EventBatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventBatchRequest(events []EventEnvelopeRequest) *EventBatchRequest {
	this := EventBatchRequest{}
	this.Events = events
	return &this
}

// NewEventBatchRequestWithDefaults instantiates a new EventBatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventBatchRequestWithDefaults() *EventBatchRequest {
	this := EventBatchRequest{}
	return &this
}

// GetEvents returns the Events field value
func (o *EventBatchRequest) GetEvents() []EventEnvelopeRequest {
	if o == nil {
		var ret []EventEnvelopeRequest
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *EventBatchRequest) GetEventsOk() ([]EventEnvelopeRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *EventBatchRequest) SetEvents(v []EventEnvelopeRequest) {
	o.Events = v
}

func (o EventBatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventBatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventBatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventBatchRequest := _EventBatchRequest{}

	err = json.Unmarshal(data, &varEventBatchRequest)

	if err != nil {
		return err
	}

	*o = EventBatchRequest(varEventBatchRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventBatchRequest struct {
	value *EventBatchRequest
	isSet bool
}

func (v NullableEventBatchRequest) Get() *EventBatchRequest {
	return v.value
}

func (v *NullableEventBatchRequest) Set(val *EventBatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventBatchRequest(val *EventBatchRequest) *NullableEventBatchRequest {
	return &NullableEventBatchRequest{value: val, isSet: true}
}

func (v NullableEventBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


