/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the SchemaCheckFailure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaCheckFailure{}

// SchemaCheckFailure struct for SchemaCheckFailure
type SchemaCheckFailure struct {
	// The stored event that fails the document.
	EventId string `json:"event_id"`
	// When the event occurred.
	OccurredAt string `json:"occurred_at"`
	// The dotted path of the offending value, or null for the root.
	Field NullableString `json:"field"`
	// What the document rejected.
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _SchemaCheckFailure SchemaCheckFailure

// NewSchemaCheckFailure instantiates a new SchemaCheckFailure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaCheckFailure(eventId string, occurredAt string, field NullableString, message string) *SchemaCheckFailure {
	this := SchemaCheckFailure{}
	this.EventId = eventId
	this.OccurredAt = occurredAt
	this.Field = field
	this.Message = message
	return &this
}

// NewSchemaCheckFailureWithDefaults instantiates a new SchemaCheckFailure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaCheckFailureWithDefaults() *SchemaCheckFailure {
	this := SchemaCheckFailure{}
	return &this
}

// GetEventId returns the EventId field value
func (o *SchemaCheckFailure) GetEventId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventId
}

// GetEventIdOk returns a tuple with the EventId field value
// and a boolean to check if the value has been set.
func (o *SchemaCheckFailure) GetEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventId, true
}

// SetEventId sets field value
func (o *SchemaCheckFailure) SetEventId(v string) {
	o.EventId = v
}

// GetOccurredAt returns the OccurredAt field value
func (o *SchemaCheckFailure) GetOccurredAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value
// and a boolean to check if the value has been set.
func (o *SchemaCheckFailure) GetOccurredAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OccurredAt, true
}

// SetOccurredAt sets field value
func (o *SchemaCheckFailure) SetOccurredAt(v string) {
	o.OccurredAt = v
}

// GetField returns the Field field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SchemaCheckFailure) GetField() string {
	if o == nil || o.Field.Get() == nil {
		var ret string
		return ret
	}

	return *o.Field.Get()
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SchemaCheckFailure) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Field.Get(), o.Field.IsSet()
}

// SetField sets field value
func (o *SchemaCheckFailure) SetField(v string) {
	o.Field.Set(&v)
}

// GetMessage returns the Message field value
func (o *SchemaCheckFailure) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SchemaCheckFailure) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SchemaCheckFailure) SetMessage(v string) {
	o.Message = v
}

func (o SchemaCheckFailure) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaCheckFailure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_id"] = o.EventId
	toSerialize["occurred_at"] = o.OccurredAt
	toSerialize["field"] = o.Field.Get()
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaCheckFailure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_id",
		"occurred_at",
		"field",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemaCheckFailure := _SchemaCheckFailure{}

	err = json.Unmarshal(data, &varSchemaCheckFailure)

	if err != nil {
		return err
	}

	*o = SchemaCheckFailure(varSchemaCheckFailure)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event_id")
		delete(additionalProperties, "occurred_at")
		delete(additionalProperties, "field")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaCheckFailure struct {
	value *SchemaCheckFailure
	isSet bool
}

func (v NullableSchemaCheckFailure) Get() *SchemaCheckFailure {
	return v.value
}

func (v *NullableSchemaCheckFailure) Set(val *SchemaCheckFailure) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaCheckFailure) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaCheckFailure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaCheckFailure(val *SchemaCheckFailure) *NullableSchemaCheckFailure {
	return &NullableSchemaCheckFailure{value: val, isSet: true}
}

func (v NullableSchemaCheckFailure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaCheckFailure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


