/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the SchemaCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaCheck{}

// SchemaCheck struct for SchemaCheck
type SchemaCheck struct {
	// How many of the newest stored events were run.
	Checked int32 `json:"checked"`
	// How many of them the document would reject.
	Failed int32 `json:"failed"`
	// The first failing events, at most 50.
	Failures []SchemaCheckFailure `json:"failures"`
	AdditionalProperties map[string]interface{}
}

type _SchemaCheck SchemaCheck

// NewSchemaCheck instantiates a new SchemaCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaCheck(checked int32, failed int32, failures []SchemaCheckFailure) *SchemaCheck {
	this := SchemaCheck{}
	this.Checked = checked
	this.Failed = failed
	this.Failures = failures
	return &this
}

// NewSchemaCheckWithDefaults instantiates a new SchemaCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaCheckWithDefaults() *SchemaCheck {
	this := SchemaCheck{}
	return &this
}

// GetChecked returns the Checked field value
func (o *SchemaCheck) GetChecked() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Checked
}

// GetCheckedOk returns a tuple with the Checked field value
// and a boolean to check if the value has been set.
func (o *SchemaCheck) GetCheckedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Checked, true
}

// SetChecked sets field value
func (o *SchemaCheck) SetChecked(v int32) {
	o.Checked = v
}

// GetFailed returns the Failed field value
func (o *SchemaCheck) GetFailed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *SchemaCheck) GetFailedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *SchemaCheck) SetFailed(v int32) {
	o.Failed = v
}

// GetFailures returns the Failures field value
func (o *SchemaCheck) GetFailures() []SchemaCheckFailure {
	if o == nil {
		var ret []SchemaCheckFailure
		return ret
	}

	return o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value
// and a boolean to check if the value has been set.
func (o *SchemaCheck) GetFailuresOk() ([]SchemaCheckFailure, bool) {
	if o == nil {
		return nil, false
	}
	return o.Failures, true
}

// SetFailures sets field value
func (o *SchemaCheck) SetFailures(v []SchemaCheckFailure) {
	o.Failures = v
}

func (o SchemaCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["checked"] = o.Checked
	toSerialize["failed"] = o.Failed
	toSerialize["failures"] = o.Failures

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchemaCheck) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"checked",
		"failed",
		"failures",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemaCheck := _SchemaCheck{}

	err = json.Unmarshal(data, &varSchemaCheck)

	if err != nil {
		return err
	}

	*o = SchemaCheck(varSchemaCheck)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "checked")
		delete(additionalProperties, "failed")
		delete(additionalProperties, "failures")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchemaCheck struct {
	value *SchemaCheck
	isSet bool
}

func (v NullableSchemaCheck) Get() *SchemaCheck {
	return v.value
}

func (v *NullableSchemaCheck) Set(val *SchemaCheck) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaCheck(val *SchemaCheck) *NullableSchemaCheck {
	return &NullableSchemaCheck{value: val, isSet: true}
}

func (v NullableSchemaCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


