/*
Santati

Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"fmt"
)

// checks if the OcsfMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OcsfMapping{}

// OcsfMapping struct for OcsfMapping
type OcsfMapping struct {
	// The OCSF release the mapping targets, e.g. 1.9.0.
	Version string `json:"version"`
	// The OCSF class the action maps to.
	ClassUid int32 `json:"class_uid"`
	// The class's activity_id enum value; 99 is Other, a best fit rather than exact.
	ActivityId int32 `json:"activity_id"`
	// The OCSF status_id the outcome sets: 2 for a failure, null when the action sets none.
	StatusId NullableInt32 `json:"status_id"`
	AdditionalProperties map[string]interface{}
}

type _OcsfMapping OcsfMapping

// NewOcsfMapping instantiates a new OcsfMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOcsfMapping(version string, classUid int32, activityId int32, statusId NullableInt32) *OcsfMapping {
	this := OcsfMapping{}
	this.Version = version
	this.ClassUid = classUid
	this.ActivityId = activityId
	this.StatusId = statusId
	return &this
}

// NewOcsfMappingWithDefaults instantiates a new OcsfMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOcsfMappingWithDefaults() *OcsfMapping {
	this := OcsfMapping{}
	return &this
}

// GetVersion returns the Version field value
func (o *OcsfMapping) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *OcsfMapping) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *OcsfMapping) SetVersion(v string) {
	o.Version = v
}

// GetClassUid returns the ClassUid field value
func (o *OcsfMapping) GetClassUid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ClassUid
}

// GetClassUidOk returns a tuple with the ClassUid field value
// and a boolean to check if the value has been set.
func (o *OcsfMapping) GetClassUidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassUid, true
}

// SetClassUid sets field value
func (o *OcsfMapping) SetClassUid(v int32) {
	o.ClassUid = v
}

// GetActivityId returns the ActivityId field value
func (o *OcsfMapping) GetActivityId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value
// and a boolean to check if the value has been set.
func (o *OcsfMapping) GetActivityIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityId, true
}

// SetActivityId sets field value
func (o *OcsfMapping) SetActivityId(v int32) {
	o.ActivityId = v
}

// GetStatusId returns the StatusId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *OcsfMapping) GetStatusId() int32 {
	if o == nil || o.StatusId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.StatusId.Get()
}

// GetStatusIdOk returns a tuple with the StatusId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OcsfMapping) GetStatusIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusId.Get(), o.StatusId.IsSet()
}

// SetStatusId sets field value
func (o *OcsfMapping) SetStatusId(v int32) {
	o.StatusId.Set(&v)
}

func (o OcsfMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OcsfMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["class_uid"] = o.ClassUid
	toSerialize["activity_id"] = o.ActivityId
	toSerialize["status_id"] = o.StatusId.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OcsfMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"class_uid",
		"activity_id",
		"status_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOcsfMapping := _OcsfMapping{}

	err = json.Unmarshal(data, &varOcsfMapping)

	if err != nil {
		return err
	}

	*o = OcsfMapping(varOcsfMapping)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "class_uid")
		delete(additionalProperties, "activity_id")
		delete(additionalProperties, "status_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOcsfMapping struct {
	value *OcsfMapping
	isSet bool
}

func (v NullableOcsfMapping) Get() *OcsfMapping {
	return v.value
}

func (v *NullableOcsfMapping) Set(val *OcsfMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableOcsfMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableOcsfMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOcsfMapping(val *OcsfMapping) *NullableOcsfMapping {
	return &NullableOcsfMapping{value: val, isSet: true}
}

func (v NullableOcsfMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOcsfMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


