<?php
/**
 * AuditEventsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Santati\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Santati
 *
 * Santati's HTTP API. Operations under `/api/v0/` take a team API key in `Authorization: Api-Key <key>`; a missing, invalid or under-scoped key is answered with `403`, never `401`. Errors on `/api/v0/` use one of three bodies: `ErrorDetail` (`{\"detail\": ...}`), `FieldErrors` (messages keyed by request field) or `ErrorEnvelope` (`{\"error\": {\"code\", \"message\", \"field\"}}`, returned by event ingestion and log stream quota checks). Lists on `/api/v0/` are cursor-paginated: follow `next` until it is `null`.
 *
 * The version of the OpenAPI document: 0.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Santati\Core\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Santati\Core\ApiException;
use Santati\Core\Configuration;
use Santati\Core\FormDataProcessor;
use Santati\Core\HeaderSelector;
use Santati\Core\ObjectSerializer;

/**
 * AuditEventsApi Class Doc Comment
 *
 * @category Class
 * @package  Santati\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditEventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'eventsCreate' => [
            'application/json',
        ],
        'eventsList' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation eventsCreate
     *
     * Send audit events
     *
     * @param  \Santati\Core\Model\EventIngestRequest $event_ingest_request event_ingest_request (required)
     * @param  string|null $idempotency_key Replay guard for a single-event request. Sending the same key again on the same trail within 24 hours returns the event already stored (&#x60;200&#x60;) instead of indexing a second one. A longer key than 255 characters is a &#x60;400 invalid_envelope&#x60;. An event&#39;s own &#x60;idempotency_key&#x60; beats this header for that event. Do not send it with a multi-event batch: it becomes the key of every event that has none of its own, and keys are scoped to the team and trail, so each later such event on the same trail is reported &#x60;duplicate&#x60; with the first event&#39;s id and is not written. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsCreate'] to see the possible values for this operation
     *
     * @throws \Santati\Core\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Santati\Core\Model\AuditEvent|\Santati\Core\Model\AuditEvent|\Santati\Core\Model\EventBatchResult|\Santati\Core\Model\EventBatchResult
     */
    public function eventsCreate($event_ingest_request, $idempotency_key = null, string $contentType = self::contentTypes['eventsCreate'][0])
    {
        list($response) = $this->eventsCreateWithHttpInfo($event_ingest_request, $idempotency_key, $contentType);
        return $response;
    }

    /**
     * Operation eventsCreateWithHttpInfo
     *
     * Send audit events
     *
     * @param  \Santati\Core\Model\EventIngestRequest $event_ingest_request (required)
     * @param  string|null $idempotency_key Replay guard for a single-event request. Sending the same key again on the same trail within 24 hours returns the event already stored (&#x60;200&#x60;) instead of indexing a second one. A longer key than 255 characters is a &#x60;400 invalid_envelope&#x60;. An event&#39;s own &#x60;idempotency_key&#x60; beats this header for that event. Do not send it with a multi-event batch: it becomes the key of every event that has none of its own, and keys are scoped to the team and trail, so each later such event on the same trail is reported &#x60;duplicate&#x60; with the first event&#39;s id and is not written. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsCreate'] to see the possible values for this operation
     *
     * @throws \Santati\Core\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Santati\Core\Model\AuditEvent|\Santati\Core\Model\AuditEvent|\Santati\Core\Model\EventBatchResult|\Santati\Core\Model\EventBatchResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventsCreateWithHttpInfo($event_ingest_request, $idempotency_key = null, string $contentType = self::contentTypes['eventsCreate'][0])
    {
        $request = $this->eventsCreateRequest($event_ingest_request, $idempotency_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Santati\Core\Model\AuditEvent',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Santati\Core\Model\AuditEvent',
                        $request,
                        $response,
                    );
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Santati\Core\Model\EventBatchResult',
                        $request,
                        $response,
                    );
                case 207:
                    return $this->handleResponseWithDataType(
                        '\Santati\Core\Model\EventBatchResult',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Santati\Core\Model\AuditEvent',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Santati\Core\Model\AuditEvent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Santati\Core\Model\AuditEvent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Santati\Core\Model\EventBatchResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Santati\Core\Model\EventBatchResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation eventsCreateAsync
     *
     * Send audit events
     *
     * @param  \Santati\Core\Model\EventIngestRequest $event_ingest_request (required)
     * @param  string|null $idempotency_key Replay guard for a single-event request. Sending the same key again on the same trail within 24 hours returns the event already stored (&#x60;200&#x60;) instead of indexing a second one. A longer key than 255 characters is a &#x60;400 invalid_envelope&#x60;. An event&#39;s own &#x60;idempotency_key&#x60; beats this header for that event. Do not send it with a multi-event batch: it becomes the key of every event that has none of its own, and keys are scoped to the team and trail, so each later such event on the same trail is reported &#x60;duplicate&#x60; with the first event&#39;s id and is not written. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsCreateAsync($event_ingest_request, $idempotency_key = null, string $contentType = self::contentTypes['eventsCreate'][0])
    {
        return $this->eventsCreateAsyncWithHttpInfo($event_ingest_request, $idempotency_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventsCreateAsyncWithHttpInfo
     *
     * Send audit events
     *
     * @param  \Santati\Core\Model\EventIngestRequest $event_ingest_request (required)
     * @param  string|null $idempotency_key Replay guard for a single-event request. Sending the same key again on the same trail within 24 hours returns the event already stored (&#x60;200&#x60;) instead of indexing a second one. A longer key than 255 characters is a &#x60;400 invalid_envelope&#x60;. An event&#39;s own &#x60;idempotency_key&#x60; beats this header for that event. Do not send it with a multi-event batch: it becomes the key of every event that has none of its own, and keys are scoped to the team and trail, so each later such event on the same trail is reported &#x60;duplicate&#x60; with the first event&#39;s id and is not written. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsCreateAsyncWithHttpInfo($event_ingest_request, $idempotency_key = null, string $contentType = self::contentTypes['eventsCreate'][0])
    {
        $returnType = '\Santati\Core\Model\AuditEvent';
        $request = $this->eventsCreateRequest($event_ingest_request, $idempotency_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventsCreate'
     *
     * @param  \Santati\Core\Model\EventIngestRequest $event_ingest_request (required)
     * @param  string|null $idempotency_key Replay guard for a single-event request. Sending the same key again on the same trail within 24 hours returns the event already stored (&#x60;200&#x60;) instead of indexing a second one. A longer key than 255 characters is a &#x60;400 invalid_envelope&#x60;. An event&#39;s own &#x60;idempotency_key&#x60; beats this header for that event. Do not send it with a multi-event batch: it becomes the key of every event that has none of its own, and keys are scoped to the team and trail, so each later such event on the same trail is reported &#x60;duplicate&#x60; with the first event&#39;s id and is not written. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function eventsCreateRequest($event_ingest_request, $idempotency_key = null, string $contentType = self::contentTypes['eventsCreate'][0])
    {

        // verify the required parameter 'event_ingest_request' is set
        if ($event_ingest_request === null || (is_array($event_ingest_request) && count($event_ingest_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_ingest_request when calling eventsCreate'
            );
        }



        $resourcePath = '/api/v0/events/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($event_ingest_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                try {
                    $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($event_ingest_request), JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                $httpBody = $event_ingest_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation eventsList
     *
     * List audit events
     *
     * @param  string|null $actor_id Exact context.actor.id. (optional)
     * @param  string|null $actor_type One of: user, system, anonymous. (optional)
     * @param  string|null $created_after RFC 3339 instant or date, inclusive, on the producer&#39;s timestamp. (optional)
     * @param  string|null $created_before Same parsing, inclusive. (optional)
     * @param  string|null $cursor Opaque cursor from the previous page. (optional)
     * @param  string|null $event Exact event type, e.g. invoice.voided. (optional)
     * @param  string|null $event_prefix Events whose type starts with this literal prefix. (optional)
     * @param  int|null $limit Page size, up to 1000. (optional)
     * @param  string|null $organization_id Producer&#39;s own organization id. (optional)
     * @param  string|null $q Full-text search over payload and metadata: at least one letter or digit, at most 200 characters, terms are ANDed prefixes. Relevance paging stops at the first 10000 matches. (optional)
     * @param  string|null $sort occurred_at (default) or relevance; relevance requires q. (optional)
     * @param  string|null $target_id Events acting on this target id. (optional)
     * @param  string|null $target_type Events acting on a target of this type. (optional)
     * @param  string|null $trail Only events from this audit log trail. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsList'] to see the possible values for this operation
     *
     * @throws \Santati\Core\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Santati\Core\Model\PaginatedAuditEventList
     */
    public function eventsList($actor_id = null, $actor_type = null, $created_after = null, $created_before = null, $cursor = null, $event = null, $event_prefix = null, $limit = null, $organization_id = null, $q = null, $sort = null, $target_id = null, $target_type = null, $trail = null, string $contentType = self::contentTypes['eventsList'][0])
    {
        list($response) = $this->eventsListWithHttpInfo($actor_id, $actor_type, $created_after, $created_before, $cursor, $event, $event_prefix, $limit, $organization_id, $q, $sort, $target_id, $target_type, $trail, $contentType);
        return $response;
    }

    /**
     * Operation eventsListWithHttpInfo
     *
     * List audit events
     *
     * @param  string|null $actor_id Exact context.actor.id. (optional)
     * @param  string|null $actor_type One of: user, system, anonymous. (optional)
     * @param  string|null $created_after RFC 3339 instant or date, inclusive, on the producer&#39;s timestamp. (optional)
     * @param  string|null $created_before Same parsing, inclusive. (optional)
     * @param  string|null $cursor Opaque cursor from the previous page. (optional)
     * @param  string|null $event Exact event type, e.g. invoice.voided. (optional)
     * @param  string|null $event_prefix Events whose type starts with this literal prefix. (optional)
     * @param  int|null $limit Page size, up to 1000. (optional)
     * @param  string|null $organization_id Producer&#39;s own organization id. (optional)
     * @param  string|null $q Full-text search over payload and metadata: at least one letter or digit, at most 200 characters, terms are ANDed prefixes. Relevance paging stops at the first 10000 matches. (optional)
     * @param  string|null $sort occurred_at (default) or relevance; relevance requires q. (optional)
     * @param  string|null $target_id Events acting on this target id. (optional)
     * @param  string|null $target_type Events acting on a target of this type. (optional)
     * @param  string|null $trail Only events from this audit log trail. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsList'] to see the possible values for this operation
     *
     * @throws \Santati\Core\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Santati\Core\Model\PaginatedAuditEventList, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventsListWithHttpInfo($actor_id = null, $actor_type = null, $created_after = null, $created_before = null, $cursor = null, $event = null, $event_prefix = null, $limit = null, $organization_id = null, $q = null, $sort = null, $target_id = null, $target_type = null, $trail = null, string $contentType = self::contentTypes['eventsList'][0])
    {
        $request = $this->eventsListRequest($actor_id, $actor_type, $created_after, $created_before, $cursor, $event, $event_prefix, $limit, $organization_id, $q, $sort, $target_id, $target_type, $trail, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Santati\Core\Model\PaginatedAuditEventList',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Santati\Core\Model\PaginatedAuditEventList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Santati\Core\Model\PaginatedAuditEventList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation eventsListAsync
     *
     * List audit events
     *
     * @param  string|null $actor_id Exact context.actor.id. (optional)
     * @param  string|null $actor_type One of: user, system, anonymous. (optional)
     * @param  string|null $created_after RFC 3339 instant or date, inclusive, on the producer&#39;s timestamp. (optional)
     * @param  string|null $created_before Same parsing, inclusive. (optional)
     * @param  string|null $cursor Opaque cursor from the previous page. (optional)
     * @param  string|null $event Exact event type, e.g. invoice.voided. (optional)
     * @param  string|null $event_prefix Events whose type starts with this literal prefix. (optional)
     * @param  int|null $limit Page size, up to 1000. (optional)
     * @param  string|null $organization_id Producer&#39;s own organization id. (optional)
     * @param  string|null $q Full-text search over payload and metadata: at least one letter or digit, at most 200 characters, terms are ANDed prefixes. Relevance paging stops at the first 10000 matches. (optional)
     * @param  string|null $sort occurred_at (default) or relevance; relevance requires q. (optional)
     * @param  string|null $target_id Events acting on this target id. (optional)
     * @param  string|null $target_type Events acting on a target of this type. (optional)
     * @param  string|null $trail Only events from this audit log trail. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsListAsync($actor_id = null, $actor_type = null, $created_after = null, $created_before = null, $cursor = null, $event = null, $event_prefix = null, $limit = null, $organization_id = null, $q = null, $sort = null, $target_id = null, $target_type = null, $trail = null, string $contentType = self::contentTypes['eventsList'][0])
    {
        return $this->eventsListAsyncWithHttpInfo($actor_id, $actor_type, $created_after, $created_before, $cursor, $event, $event_prefix, $limit, $organization_id, $q, $sort, $target_id, $target_type, $trail, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventsListAsyncWithHttpInfo
     *
     * List audit events
     *
     * @param  string|null $actor_id Exact context.actor.id. (optional)
     * @param  string|null $actor_type One of: user, system, anonymous. (optional)
     * @param  string|null $created_after RFC 3339 instant or date, inclusive, on the producer&#39;s timestamp. (optional)
     * @param  string|null $created_before Same parsing, inclusive. (optional)
     * @param  string|null $cursor Opaque cursor from the previous page. (optional)
     * @param  string|null $event Exact event type, e.g. invoice.voided. (optional)
     * @param  string|null $event_prefix Events whose type starts with this literal prefix. (optional)
     * @param  int|null $limit Page size, up to 1000. (optional)
     * @param  string|null $organization_id Producer&#39;s own organization id. (optional)
     * @param  string|null $q Full-text search over payload and metadata: at least one letter or digit, at most 200 characters, terms are ANDed prefixes. Relevance paging stops at the first 10000 matches. (optional)
     * @param  string|null $sort occurred_at (default) or relevance; relevance requires q. (optional)
     * @param  string|null $target_id Events acting on this target id. (optional)
     * @param  string|null $target_type Events acting on a target of this type. (optional)
     * @param  string|null $trail Only events from this audit log trail. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsListAsyncWithHttpInfo($actor_id = null, $actor_type = null, $created_after = null, $created_before = null, $cursor = null, $event = null, $event_prefix = null, $limit = null, $organization_id = null, $q = null, $sort = null, $target_id = null, $target_type = null, $trail = null, string $contentType = self::contentTypes['eventsList'][0])
    {
        $returnType = '\Santati\Core\Model\PaginatedAuditEventList';
        $request = $this->eventsListRequest($actor_id, $actor_type, $created_after, $created_before, $cursor, $event, $event_prefix, $limit, $organization_id, $q, $sort, $target_id, $target_type, $trail, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventsList'
     *
     * @param  string|null $actor_id Exact context.actor.id. (optional)
     * @param  string|null $actor_type One of: user, system, anonymous. (optional)
     * @param  string|null $created_after RFC 3339 instant or date, inclusive, on the producer&#39;s timestamp. (optional)
     * @param  string|null $created_before Same parsing, inclusive. (optional)
     * @param  string|null $cursor Opaque cursor from the previous page. (optional)
     * @param  string|null $event Exact event type, e.g. invoice.voided. (optional)
     * @param  string|null $event_prefix Events whose type starts with this literal prefix. (optional)
     * @param  int|null $limit Page size, up to 1000. (optional)
     * @param  string|null $organization_id Producer&#39;s own organization id. (optional)
     * @param  string|null $q Full-text search over payload and metadata: at least one letter or digit, at most 200 characters, terms are ANDed prefixes. Relevance paging stops at the first 10000 matches. (optional)
     * @param  string|null $sort occurred_at (default) or relevance; relevance requires q. (optional)
     * @param  string|null $target_id Events acting on this target id. (optional)
     * @param  string|null $target_type Events acting on a target of this type. (optional)
     * @param  string|null $trail Only events from this audit log trail. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['eventsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function eventsListRequest($actor_id = null, $actor_type = null, $created_after = null, $created_before = null, $cursor = null, $event = null, $event_prefix = null, $limit = null, $organization_id = null, $q = null, $sort = null, $target_id = null, $target_type = null, $trail = null, string $contentType = self::contentTypes['eventsList'][0])
    {
















        $resourcePath = '/api/v0/events/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $actor_id,
            'actor_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $actor_type,
            'actor_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_after,
            'created_after', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_before,
            'created_before', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $event,
            'event', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $event_prefix,
            'event_prefix', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $organization_id,
            'organization_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $target_id,
            'target_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $target_type,
            'target_type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $trail,
            'trail', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
